[package]
name = "n8n-expression"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
n8n-common = { path = "../n8n-common" }
n8n-execution-data = { path = "../n8n-execution-data" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
regex = "1.10"
