/**
 * The merged master specification (`.ai/master/`): one canonical document per subject.
 *
 * After the P2.11 reconciliation the master set has two owners and two natures:
 *
 *   - eleven documents are GENERATED from Agent 2's manifests by `tools/lego/ai-pack.mjs`
 *     (they carry the banner and `npm run lego:ai:check` fails if they drift);
 *   - eighteen documents are hand-written by agent-1 (the frontend consumption views and the
 *     frontend record: AI UI experience, states, disclosure, accessibility, contracts, phases,
 *     status) plus the platform strategy and the topic plans.
 *
 * These tests keep the union honest: both halves exist, the generated half is in sync with its
 * manifests, the canonical counts are the manifest's, no retired claim survives anywhere in the
 * memory, development-workforce material stays out of product manifests, and every question a new
 * agent is supposed to be able to answer resolves to a document that exists.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { existsSync, readFileSync, readdirSync, statSync } from 'node:fs';
import { join } from 'node:path';

import { PACKAGE_ROOT } from '../src/manifests.mjs';
import {
  MASTER_PLAN_BUDGET,
  MASTER_PLAN_FILES,
  MASTER_PLAN_MAX_FILE,
  PRODUCT_TASK_INDEX,
  masterPlanFiles,
  packFiles,
  productContextFor,
} from '../src/knowledge.mjs';

const REPO_ROOT = join(PACKAGE_ROOT, '..', '..');
const read = (relative) => readFileSync(join(REPO_ROOT, relative), 'utf8');
const size = (relative) => statSync(join(REPO_ROOT, relative)).size;
const readJson = (relative) => JSON.parse(read(relative));

const MASTER = masterPlanFiles();
const BANNER = 'GENERATED by tools/lego/ai-pack.mjs';
const MANIFEST = 'apps/n8n-lego/src/lego/manifest';
const GENERATED = new Set(MASTER.filter((file) => read(file).includes(BANNER)));

const walk = (dir, out = []) => {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const absolute = join(dir, entry.name);
    if (entry.isDirectory()) walk(absolute, out);
    else out.push(absolute);
  }
  return out;
};

test('every master document exists, is a document, and can be read on its own', () => {
  assert.equal(MASTER.length, Object.keys(MASTER_PLAN_FILES).length);
  assert.ok(MASTER.length >= 25, `${MASTER.length} master documents`);
  for (const file of MASTER) {
    assert.ok(file.startsWith('.ai/master/'), `${file} lives in the master area`);
    assert.ok(existsSync(join(REPO_ROOT, file)), `${file} exists`);
    const body = read(file);
    assert.match(body, /^# /m, `${file} opens with a title`);
    assert.ok(size(file) > 1500, `${file} says something (${size(file)} B)`);
  }
});

test('the master set is a union of a generated half and a hand-written half', () => {
  assert.equal(GENERATED.size, 11, `${GENERATED.size} generated documents`);
  assert.ok(MASTER.length - GENERATED.size >= 18, `${MASTER.length - GENERATED.size} hand-written documents`);
  for (const file of GENERATED) {
    assert.match(read(file), /do not edit by hand/, `${file} declares itself generated`);
  }
  for (const file of MASTER.filter((candidate) => !GENERATED.has(candidate))) {
    assert.equal(read(file).includes('do not edit by hand'), false, `${file} is hand-written and says so by omission`);
  }
  // The agent-1 record and the generated backend record are both present.
  assert.ok(GENERATED.has('.ai/master/PROJECT_MASTER_PLAN.md'), 'the backend index is generated');
  assert.ok(!GENERATED.has('.ai/master/FRONTEND_STATUS.md'), 'the frontend record is hand-written');
});

test('the generated half is in sync with its manifests, byte for byte', () => {
  const result = spawnSync('node', ['tools/lego/ai-pack.mjs', '--check'], { cwd: REPO_ROOT, encoding: 'utf8' });
  assert.equal(result.status, 0, `ai-pack --check failed: ${result.stdout}${result.stderr}`);
  assert.match(result.stdout, /in sync with the manifest/, 'the check reports the sync');
});

test('the specification is budgeted: 512 KB in total, 32 KB per document', () => {
  const total = MASTER.reduce((sum, file) => sum + size(file), 0);
  assert.ok(total <= MASTER_PLAN_BUDGET, `the master set is ${total} B — budget ${MASTER_PLAN_BUDGET} B`);
  for (const file of MASTER) {
    assert.ok(size(file) <= MASTER_PLAN_MAX_FILE, `${file} is ${size(file)} B — max ${MASTER_PLAN_MAX_FILE} B`);
  }
});

test('the canonical counts are the manifests, and the generated documents state them', () => {
  const registry = readJson(`${MANIFEST}/domains.json`);
  const set = readJson(`${MANIFEST}/ai-lego-set.json`);
  const errors = readJson('apps/n8n-lego/src/lego/contracts/errors.contract.json');
  const capabilities = registry.domains.flatMap((domain) => domain.capabilities ?? []);
  const operations = capabilities.reduce((sum, capability) => sum + (capability.operations ?? []).length, 0);
  assert.equal(registry.domains.length, 26, '26 core domains');
  assert.equal(capabilities.length, 82, '82 capabilities');
  assert.equal(operations, 139, '139 operations');
  assert.equal(set.lego.length, 15, '15 official AI/Agent LEGO');
  assert.equal(errors.codes.length, 35, '35 published error codes');
  const plan = read(MASTER_PLAN_FILES.project);
  for (const count of ['26', '15', '82', '35']) {
    assert.ok(plan.includes(`| ${count} |`) || plan.includes(`**${count}**`), `the master plan states ${count}`);
  }
  const coreLego = read(MASTER_PLAN_FILES.coreLego);
  assert.match(coreLego, /26/, 'the core LEGO document states the domain count');
});

test('no retired claim survives anywhere in the project memory', () => {
  const offenders = [];
  // The project memory must not assert a retired count. `docs/n8n-lego/BACKEND_LEGO.md` is the
  // change log that records the correction ("previously said 173 operations"), so it is read for
  // the assertion that the canonical number is 139 instead.
  for (const absolute of walk(join(REPO_ROOT, '.ai'))) {
    if (!/\.(md|json)$/.test(absolute)) continue;
    const body = readFileSync(absolute, 'utf8');
    if (/\b25\s+(core\s+)?(LEGO\s+)?domains?\b/i.test(body)) offenders.push(`${absolute}: claims 25 domains`);
    if (/\b173\s+operations\b/i.test(body)) offenders.push(`${absolute}: claims 173 operations`);
  }
  const backendDoc = read('docs/n8n-lego/BACKEND_LEGO.md');
  assert.match(backendDoc, /173 operations/, 'the change log records the retired claim');
  assert.match(backendDoc, /139/, 'and the canonical number that replaced it');
  assert.deepEqual(offenders, [], offenders.join('\n'));
});

test('development-workforce material never becomes product architecture', () => {
  const productManifests = {
    'domains.json': `${MANIFEST}/domains.json`,
    'ai-foundation.json': `${MANIFEST}/ai-foundation.json`,
    'ai-lego-set.json': `${MANIFEST}/ai-lego-set.json`,
    'contract-lock.json': 'apps/n8n-lego/src/lego/contracts/contract-lock.json',
    'errors.contract.json': 'apps/n8n-lego/src/lego/contracts/errors.contract.json',
  };
  for (const [manifest, path] of Object.entries(productManifests)) {
    const body = read(path).toLowerCase();
    for (const forbidden of ['arena', 'supabase', 'manager/worker', 'worker branch']) {
      assert.equal(body.includes(forbidden), false, `${manifest} must not reference ${forbidden}`);
    }
  }
  const workforce = read(MASTER_PLAN_FILES.workforce);
  assert.match(workforce, /NOT product architecture/i, 'the workforce document says what it is not');
  assert.match(workforce, /no product manifest/i, 'and that no product manifest may reference it');
  const plan = read(MASTER_PLAN_FILES.project);
  assert.match(plan, /engineering operations/i, 'the index labels it as engineering operations');
});

test('one canonical document per subject, and every product task resolves to one', () => {
  const plan = read(MASTER_PLAN_FILES.project);
  for (const subject of ['Project overview', 'official AI/Agent LEGO', 'Providers, runtimes', 'Phase roadmap', 'Decisions and open arbitration', 'core domains', 'scenarios', 'What is true today', 'blocking progress', 'Frontend AI architecture', 'Frontend UI states', 'Frontend contract matrix', 'Frontend status']) {
    assert.ok(plan.includes(subject), `the index names a canonical document for: ${subject}`);
  }
  // The generated index is the reader test; it must stay answerable.
  const rows = [...plan.matchAll(/^\| (.+?) \| (.+?) \|$/gm)];
  assert.ok(rows.length >= 30, `the index maps ${rows.length} answers`);
  for (const [, , target] of rows) {
    for (const match of target.matchAll(/`([A-Z0-9_]+\.md)`/g)) {
      assert.ok(MASTER.some((file) => file.endsWith('/' + match[1])), `${match[1]} is a master document`);
    }
  }
  const seen = new Set();
  for (const kind of Object.keys(PRODUCT_TASK_INDEX)) {
    const resolved = productContextFor({ kind });
    assert.equal(resolved.kind, kind, `${kind} resolves to itself`);
    assert.ok(resolved.question.endsWith('?'), `${kind} asks a question`);
    for (const file of resolved.files) {
      assert.ok(MASTER.includes(file), `${kind} resolves to a master document (${file})`);
      seen.add(file);
    }
  }
  assert.ok(seen.size >= 20, `${seen.size} of ${MASTER.length} documents are reachable from a product task`);
  assert.equal(productContextFor({ kind: 'ai-everything' }).kind, 'project', 'an unknown task fails closed');
});

test('the registers stay open, evidenced and reconciled', () => {
  const frontend = readJson('docs/n8n-lego/decisions/cross-agent-decisions.json');
  const backend = readJson('docs/n8n-lego/decisions/cross-agent-decisions.backend.json');
  assert.ok(frontend.decisions.length >= 18, `${frontend.decisions.length} frontend rows`);
  for (const row of frontend.decisions) {
    assert.match(row.id, /^XA-\d+$/);
    assert.ok(['resolved', 'open-for-agent-2', 'open-for-manager'].includes(row.status), `${row.id} has a known status`);
    assert.ok((row.evidence ?? []).length >= 2, `${row.id} cites evidence`);
    assert.ok(row.owner && row.affectedDomains?.length && row.blockingLevel && row.date, `${row.id} carries the required fields`);
  }
  const recorded = new Set(frontend.decisions.map((row) => row.id));
  for (const row of backend.decisions ?? backend.rows ?? []) recorded.add(row.id);
  const named = new Set();
  for (const file of MASTER) for (const match of read(file).matchAll(/XA-\d+/g)) named.add(match[0]);
  assert.ok(named.size >= 8, `${named.size} decision ids are named across the specification`);
  for (const id of named) {
    if (/^XA-\d+$/.test(id)) continue; // XA refs come only from these registers
  }
  const known = new Set([...recorded]);
  const unknown = [...named].filter((id) => !known.has(id));
  assert.deepEqual(unknown, [], `every decision id named by the memory exists in a register: ${unknown.join(', ')}`);
});

test('the specification is not retrieval context: it never enters the pack', () => {
  const pack = packFiles();
  for (const file of MASTER) {
    assert.equal(pack.includes(file), false, `${file} is loaded on purpose, not by default`);
  }
  assert.ok(pack.some((file) => file.startsWith('.ai/frontend/')), 'the pack still has its own levels');
});
