// Manager memory views (#259 §6, #262 §4). Deterministic, generated from control-plane state.
// These files are DERIVED views: the authoritative state is the object store + event log, and
// canonical rules stay on main. Regenerate instead of hand-editing.
import { isTerminal } from './core.mjs';
import { plan } from './scheduler.mjs';
import { reconcile, snapshot } from './recovery.mjs';

const HEADER = (title, now, digest) => `# ${title}\n\n> Generated by \`tools/workforce\` at ${now} (policy ${digest.slice(0, 19)}…). Derived view — do not hand-edit.\n\n`;
const esc = (v) => String(v ?? '—').replace(/\|/g, '\\|').replace(/\n/g, ' ');
const table = (cols, rows) => (rows.length
  ? `| ${cols.join(' | ')} |\n|${cols.map(() => '---').join('|')}|\n${rows.map((r) => `| ${r.map(esc).join(' | ')} |`).join('\n')}\n`
  : '_none_\n');

export function renderMemory(controlPlane, now, repo = {}) {
  const { policy, policyDigest: digest, store } = controlPlane;
  const s = snapshot(store);
  const sched = plan({ tasks: s.Task, agents: s.AgentState, reservations: s.Reservation }, policy, now);
  const rec = reconcile(store, policy, now);
  const openTasks = s.Task.filter((t) => !isTerminal(policy, 'Task', t.state));
  const files = {};

  files['AGENTS.md'] = HEADER('Agents', now, digest) + table(
    ['Agent', 'State', 'Branch', 'Capabilities', 'Runner', 'Active', 'Tasks', 'Last seen', 'Health'],
    s.AgentState.map((a) => [a.objectId, a.state, a.slot, a.capabilities.join(', '), a.capacity.runnerClass, `${a.capacity.activeTaskCount}/${a.capacity.maxConcurrentTasks}`, (a.assignment?.taskIds ?? []).join(', '), a.heartbeat?.lastSeenAt, a.health?.status]),
  );
  files['TASKS.md'] = HEADER('Tasks', now, digest) + table(
    ['Task', 'State', 'Program', 'Slice', 'Priority', 'Owner', 'Lease', 'Head', 'Next action'],
    openTasks.map((t) => [t.objectId, t.state, t.program, t.slice, t.priority, t.owner?.agentId, t.execution.activeLeaseId, t.current.headSha?.slice(0, 12), t.current.nextAction]),
  ) + `\n## Closed\n\n${table(['Task', 'State', 'Main SHA'], s.Task.filter((t) => isTerminal(policy, 'Task', t.state)).map((t) => [t.objectId, t.state, t.current.completedMainSha?.slice(0, 12)]))}`;
  // DEC-0014: Slice = delivery boundary (one delivery PR per Slice); Task = execution boundary.
  files['SLICES.md'] = HEADER('Slices (delivery units)', now, digest) + table(
    ['Slice', 'Key', 'State', 'Program', 'Title', 'Tasks', 'Delivery PR', 'Exact head', 'Merge SHA', 'Acceptance', 'Register'],
    s.Slice.map((sl) => {
      const tasks = s.Task.filter((t) => t.slice === sl.key);
      const met = sl.acceptance.criteria.filter((c) => c.met).length;
      return [sl.objectId, sl.key, sl.state, sl.program, sl.title, tasks.map((t) => `${t.objectId}(${t.state})`).join(', '), sl.delivery.prNumber ? `#${sl.delivery.prNumber}` : null,
        sl.delivery.headSha?.slice(0, 12), sl.delivery.mergeSha?.slice(0, 12), `${met}/${sl.acceptance.criteria.length}`, sl.milestoneRegister ? sl.milestoneRegister.commitSha.slice(0, 12) : null];
    }),
  ) + `\nInvariant: ${policy.slices?.invariant ?? 'n/a'}\n`;
  files['MERGE-QUEUE.md'] = HEADER('Merge queue', now, digest) + table(
    ['Item', 'State', 'Lane', 'PR', 'Exact head', 'Checks', 'Rollback', 'Reasons'],
    s.MergeQueueItem.filter((m) => !isTerminal(policy, 'MergeQueueItem', m.state)).map((m) => [m.objectId, m.state, m.lane, `#${m.pr.number}`, m.pr.headSha.slice(0, 12), Object.entries(m.checks).filter(([k]) => k !== 'checkedHeadSha').map(([k, v]) => `${k}:${v}`).join(' '), m.rollback.class, (m.laneReasons ?? []).slice(0, 3).join('; ')]),
  );
  const blockers = [
    ...openTasks.filter((t) => ['BLOCKED', 'WAITING_EXTERNAL', 'HOLD', 'FROZEN'].includes(t.state)).map((t) => [t.objectId, t.state, t.current.blocker?.code ?? t.current.reason?.code, t.current.blocker?.summary ?? t.current.reason?.summary]),
    ...openTasks.filter((t) => !['BLOCKED', 'WAITING_EXTERNAL', 'HOLD', 'FROZEN'].includes(t.state) && (t.execution.hold || t.execution.decisionPending)).map((t) => [t.objectId, t.execution.hold ? 'ON_HOLD' : 'DECISION_PENDING', t.state, t.current.nextAction]),
    ...s.Request.filter((r) => r.state === 'OPEN').map((r) => [r.objectId, r.kind, r.requestedBy, r.summary]),
  ];
  files['BLOCKERS.md'] = HEADER('Blockers & open requests', now, digest) + table(['Ref', 'State/Kind', 'Code/By', 'Summary'], blockers);
  files['BOTTLENECKS.md'] = HEADER('Bottlenecks', now, digest)
    + `Capacity: ${sched.capacity.active}/${sched.capacity.maxActiveTasks} active, ${sched.capacity.queued} queued, ${sched.capacity.plannedAssignments} assignable now.\n\n`
    + `## Deferred work\n\n${table(['Task', 'Effective priority', 'Why not scheduled'], sched.deferred.map((d) => [d.taskId, d.priority.effective, d.reasons.join('; ')]))}\n`
    + `## Alerts\n\n${table(['Kind', 'Subject', 'Reasons'], sched.alerts.map((a) => [a.kind, a.taskId ?? a.agentId ?? '—', a.reasons.join('; ')]))}\n`
    + `## Cross-program concurrency\n\n${Object.entries(sched.concurrency.summary).map(([k, v]) => `- ${k}: ${v}`).join('\n')}\n\n${table(['A', 'B', 'Programs', 'Class', 'Reason'], sched.concurrency.pairs.map((p) => [p.a, p.b, p.programs.join(' × '), p.class, p.reason]))}`;
  files['HANDOFFS.md'] = HEADER('Handoffs', now, digest) + table(
    ['Handoff', 'Task', 'Author', 'Commit', 'Next action', 'Decision needed'],
    s.Handoff.map((h) => [h.objectId, h.taskId, h.author, h.commitSha?.slice(0, 12), h.nextAction, h.managerDecisionRequired ? 'yes' : 'no']),
  );
  files['JOURNAL.md'] = HEADER('Journal', now, digest) + (s.JournalEntry.length
    ? s.JournalEntry.map((j) => `- **${j.objectId}** [${j.kind}] ${j.createdAt} ${j.author}: ${j.summary}${j.refs.length ? ` (${j.refs.join(', ')})` : ''}`).join('\n') + '\n'
    : '_none_\n');
  files['LESSONS.md'] = HEADER('Lessons', now, digest) + (s.JournalEntry.filter((j) => j.kind === 'LESSON').map((j) => `- ${j.summary} (${j.objectId})`).join('\n') || '_none_') + '\n';
  files['DECISIONS.md'] = HEADER('Decision register (operational view)', now, digest) + table(
    ['Decision', 'State', 'Category', 'Title', 'Supersedes', 'Canonical on main'],
    s.Decision.map((d) => [d.objectId, d.state, d.category, d.title, d.supersedes, d.promotion.canonical ? d.promotion.mainCommitSha.slice(0, 12) : 'no']),
  );
  files['RESERVATIONS.md'] = HEADER('Reservations & leases', now, digest)
    + table(['Reservation', 'State', 'Task', 'Mode', 'Parallelism', 'Expires', 'Conflicts'], s.Reservation.filter((r) => !isTerminal(policy, 'Reservation', r.state)).map((r) => [r.objectId, r.state, r.taskId, r.mode, r.parallelism, r.expiresAt, r.conflicts.map((c) => `${c.reservationId}/${c.dimension}/${c.compatibility}`).join(', ')]))
    + `\n## Active leases\n\n${table(['Lease', 'Type', 'Holder', 'Subject', 'Expires', 'Renewals'], s.Lease.filter((l) => l.state === 'ACTIVE').map((l) => [l.objectId, l.leaseType, l.holder, l.subject.taskId ?? l.subject.queueItemId, l.expiresAt, l.renewCount]))}`;
  files['RECOVERY.md'] = HEADER('Recovery & reconciliation', now, digest)
    + `Events in log: ${rec.events}\n\n${table(['Finding', 'Object', 'Detail'], rec.findings.map((f) => [f.kind, f.object ?? f.eventId ?? '—', JSON.stringify(Object.fromEntries(Object.entries(f).filter(([k]) => !['kind', 'object'].includes(k))))]))}\n## Proposed commands\n\n${table(['Command', 'Target', 'Safe', 'Note'], rec.proposals.map((p) => [p.commandType, `${p.target.objectType}/${p.target.objectId}`, p.safe ? 'auto' : 'Manager', p.note]))}`;
  files['CURRENT.md'] = HEADER('Current', now, digest) + statusReport(controlPlane, now, repo, { s, sched, rec });
  return files;
}

/** MANAGER STATUS report (master prompt §47). */
export function statusReport(controlPlane, now, repo = {}, pre) {
  const { policy, store } = controlPlane;
  const s = pre?.s ?? snapshot(store);
  s.Slice ??= [];
  const sched = pre?.sched ?? plan({ tasks: s.Task, agents: s.AgentState, reservations: s.Reservation }, policy, now);
  const rec = pre?.rec ?? reconcile(store, policy, now);
  const count = (arr, key = 'state') => Object.entries(arr.reduce((m, o) => ({ ...m, [o[key]]: (m[o[key]] ?? 0) + 1 }), {})).map(([k, v]) => `${k} ${v}`).join(', ') || 'none';
  const programs = [...new Set(s.Task.map((t) => t.program))].sort().map((p) => `${p}: ${count(s.Task.filter((t) => t.program === p))}`).join('; ') || 'none';
  const lines = [
    `MANAGER STATUS (${now})`,
    `MAIN: ${repo.main ?? 'unverified'}`,
    `ARENA-MANAGER: ${repo.arenaManager ?? 'unverified'}`,
    `WORKERS: ${count(s.AgentState)}`,
    `SLICES: ${count(s.Slice)}`,
    `TASKS: ${count(s.Task)}`,
    `PROGRAMS: ${programs}`,
    `RESERVATIONS: ${count(s.Reservation.filter((r) => !isTerminal(policy, 'Reservation', r.state)))}`,
    `LEASES: ${count(s.Lease.filter((l) => l.state === 'ACTIVE'), 'leaseType')}`,
    `MERGE QUEUE: ${count(s.MergeQueueItem.filter((m) => !isTerminal(policy, 'MergeQueueItem', m.state)))}`,
    `DECISIONS: ${count(s.Decision)}`,
    `RECOVERY: ${rec.findings.length} findings, ${rec.proposals.length} proposals`,
    `BLOCKERS: ${[
      ...s.Task.filter((t) => ['BLOCKED', 'HOLD', 'FROZEN', 'WAITING_EXTERNAL'].includes(t.state)).map((t) => `${t.objectId}(${t.state})`),
      // Unstarted work can be blocked too: a hold flag or a pending Manager decision.
      ...s.Task.filter((t) => !isTerminal(policy, 'Task', t.state) && !['BLOCKED', 'HOLD', 'FROZEN', 'WAITING_EXTERNAL'].includes(t.state) && (t.execution.hold || t.execution.decisionPending))
        .map((t) => `${t.objectId}(${t.execution.hold ? 'ON_HOLD' : 'DECISION_PENDING'})`),
      ...s.Request.filter((r) => r.state === 'OPEN' && r.kind === 'BLOCKER_REPORT').map((r) => `${r.objectId}(BLOCKER_REPORT)`),
      ...(repo.blockers ?? []),
    ].join(', ') || 'none'}`,
    `COMPLETED: ${s.Task.filter((t) => t.state === 'COMPLETED').map((t) => t.objectId).join(', ') || 'none'}`,
    `NEXT: ${sched.assignments.map((a) => `assign ${a.taskId}->${a.agentId}`).concat(sched.alerts.map((a) => `${a.kind} ${a.taskId ?? a.agentId ?? ''}`.trim())).slice(0, 8).join('; ') || 'no schedulable work'}`,
  ];
  return `${lines.join('\n')}\n`;
}
