// Agent 2: Node Parameter Label & Action Catalog Form Field Sanitizer
export const NODE_ACTIONS_AND_PARAMS = {
  id: {
    "CHAT ACTIONS": "AKSI OBROLAN",
    "CALLBACK ACTIONS": "AKSI CALLBACK",
    "FILE ACTIONS": "AKSI BERKAS",
    "MESSAGE ACTIONS": "AKSI PESAN",
    "Get a chat": "Ambil data obrolan",
    "Get all administrators in a chat": "Ambil semua admin obrolan",
    "Get a member in a chat": "Ambil anggota obrolan",
    "Leave a chat": "Keluar dari obrolan",
    "Set description on a chat": "Atur deskripsi obrolan",
    "Set a title on a chat": "Atur judul obrolan",
    "Answer Query a callback": "Jawab kueri panggilan balik",
    "Answer an inline query callback": "Jawab kueri inline callback",
    "Get a file": "Ambil berkas",
    "Delete a chat message": "Hapus pesan obrolan",
    "Edit a text message": "Edit pesan teks",
    "Pin a chat message": "Sematkan pesan obrolan",
    "Send an animated file": "Kirim berkas animasi (GIF)",
    "Send a chat action": "Kirim aksi obrolan",
    "Send a document": "Kirim dokumen",
    "Send a media group": "Kirim grup media",
    "Send a photo": "Kirim foto",
    "Send a text message": "Kirim pesan teks",
    "Send a video": "Kirim video",
    "Unpin a chat message": "Lepas sematan pesan",
    "Search Telegram Actions...": "Cari Aksi Telegram...",
    "Chat ID": "ID Obrolan",
    "Text": "Teks Pesan",
    "Operation": "Operasi",
    "Resource": "Sumber Daya",
    "Credential to connect with": "Kredensial untuk terhubung"
  },
  jv: {
    "CHAT ACTIONS": "AKSI REMBUGAN",
    "FILE ACTIONS": "AKSI BERKAS",
    "MESSAGE ACTIONS": "AKSI PESEN",
    "Get a chat": "Jupuk data rembugan",
    "Delete a chat message": "Busek pesen rembugan",
    "Edit a text message": "Owahi pesen teks",
    "Pin a chat message": "Sematake pesen rembugan",
    "Send a text message": "Kirim pesen teks",
    "Chat ID": "ID Rembugan",
    "Text": "Teks Pesen",
    "Operation": "Operasi",
    "Resource": "Sumber Daya",
    "Credential to connect with": "Kredensial kanggo nyambung"
  },
  ar: {
    "CHAT ACTIONS": "إجراءات المحادثة",
    "FILE ACTIONS": "إجراءات الملفات",
    "MESSAGE ACTIONS": "إجراءات الرسائل",
    "Get a chat": "الحصول على المحادثة",
    "Delete a chat message": "حذف رسالة محادثة",
    "Edit a text message": "تعديل رسالة نصية",
    "Pin a chat message": "تثبيت رسالة محادثة",
    "Send a text message": "إرسال رسالة نصية",
    "Chat ID": "معرف المحادثة",
    "Text": "نص الرسالة",
    "Operation": "العملية",
    "Resource": "المورد",
    "Credential to connect with": "بيانات الاعتماد للاتصال"
  },
  zh: {
    "CHAT ACTIONS": "聊天操作",
    "FILE ACTIONS": "文件操作",
    "MESSAGE ACTIONS": "消息操作",
    "Get a chat": "获取聊天",
    "Delete a chat message": "删除聊天消息",
    "Edit a text message": "编辑文本消息",
    "Pin a chat message": "置顶聊天消息",
    "Send a text message": "发送文本消息",
    "Chat ID": "聊天 ID",
    "Text": "消息文本",
    "Operation": "操作",
    "Resource": "资源",
    "Credential to connect with": "连接凭证"
  },
  ru: {
    "CHAT ACTIONS": "ДЕЙСТВИЯ С ЧАТОМ",
    "FILE ACTIONS": "ДЕЙСТВИЯ С ФАЙЛАМИ",
    "MESSAGE ACTIONS": "ДЕЙСТВИЯ С СООБЩЕНИЯМИ",
    "Get a chat": "Получить чат",
    "Delete a chat message": "Удалить сообщение чата",
    "Edit a text message": "Редактировать текстовое сообщение",
    "Pin a chat message": "Закрепить сообщение чата",
    "Send a text message": "Отправить текстовое сообщение",
    "Chat ID": "ID чата",
    "Text": "Текст сообщения",
    "Operation": "Операция",
    "Resource": "Ресурс",
    "Credential to connect with": "Учетные данные для подключения"
  }
};
