#!/usr/bin/env node
/**
 * AI architecture knowledge pack generator (P2.8-B, §40–45).
 *
 *   node tools/lego/ai-pack.mjs            # regenerate .ai/
 *   node tools/lego/ai-pack.mjs --check    # fail if .ai/ is stale (CI)
 *
 * WHY GENERATED: a hand-written `.ai/` folder is a second registry, and a second
 * registry always drifts from the first. Everything here is derived from the
 * manifest, the contract lock and the foundation vocabulary — the same data the
 * gates enforce. `--check` makes staleness a build failure, so the pack is
 * either correct or the build is red.
 *
 * CONTEXT LEVELS (§45) — an agent reads the smallest level that answers it:
 *   L0 constitution.md   always; ~40 lines
 *   L1 domains/<id>.md   one LEGO card
 *   L2 contracts.md      the contract and its version rules
 *   L3 recipes/<id>.md   a step-by-step SOP
 *   L4 the source        only when L0–L3 are insufficient
 *
 * Owner: manager. Pure Node, no dependencies.
 */
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { loadRegistry, getChildren, CONTRACT_LOCK_FILE, MANIFEST_FILE } from '../../apps/n8n-lego/src/lego/registry.mjs';
import { FOUNDATION, NODE_CONTRACT } from '../../apps/n8n-lego/src/lego/foundation.mjs';
import { buildGraph, impactOf, TEST_TIERS } from './impact-graph.mjs';

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');
const AI_ROOT = join(REPO_ROOT, '.ai');
const LOCK = JSON.parse(readFileSync(CONTRACT_LOCK_FILE, 'utf8'));

const BANNER = '<!-- GENERATED by tools/lego/ai-pack.mjs — do not edit by hand. Run `npm run lego:ai` after changing the manifest. -->';

/* ------------------------------------------------------------ L0 constitution */

function constitution() {
  return `${BANNER}
# AI Constitution — n8n LEGO backend

Ten rules. If a change violates one, it is wrong regardless of how well it works.

1. **Never reach into another LEGO's internals.** Only its public contract.
2. **Prefer the direct local call.** In-process is the default; everything else must earn its cost.
3. **No internal HTTP without a real process boundary.** Localhost HTTP between two LEGOs in the same process is pure overhead pretending to be architecture.
4. **Never break n8n editor-UI compatibility.** The wire contract is \`{data}\`, \`{count,data}\`, \`{message,code?,meta?}\`, and 501 for known-but-unimplemented.
5. **Smallest viable implementation.** The correct amount of framework is usually none.
6. **Prefer Rust only on material benefit** — high-frequency execution, real resource saving, or long-term maintainability. Never because it is Rust.
7. **WASM is for portability and sandboxing**, not for speed theatre.
8. **Never break a contract for implementation convenience.** Change the implementation; the contract is the promise.
9. **A contract change needs a version decision, a migration declaration, tests and controlled activation.** In that order.
10. **Declare, do not assume.** Capabilities, data ownership, state class, resources and trust are declared in the manifest or they do not exist.

## Before you change anything

\`\`\`
node tools/lego/impact-graph.mjs --plan --target <lego-id> --change "<what>"
\`\`\`

Then run the test tier it selects, then \`npm run lego:gate\`.

## Context levels — read the smallest that answers your question

| Level | File | Use it for |
| --- | --- | --- |
| L0 | \`.ai/constitution.md\` | always |
| L1 | \`.ai/domains/<id>.md\` | what one LEGO owns and may call |
| L2 | \`.ai/contracts.md\` | the contract, its version, its lock row |
| L2 | \`.ai/communication.md\` | CALL/EVENT/STREAM/BATCH, envelope, cancellation, backpressure |
| L3 | \`.ai/recipes/<id>.md\` | how to perform a specific change |
| L4 | the source | only when L0–L3 are insufficient |

## Current honest status

- The backend is **not scale-out ready**. See \`.ai/scale-out.md\`. Do not claim otherwise.
- Rust is **locked**. JavaScript is the active backend.
- Feature domains (Workflow, Execution, Auth, Node Registry, Storage) are **declared, not implemented**.
- The legacy REST aggregate is frozen and may only shrink — see \`.ai/legacy-rest.md\`.
- Allowances remaining: see \`.ai/index.md\`. They may shrink, never grow.
`;
}

/* ---------------------------------------------------------------- L1 domains */

function domainCard(domain, registry, graph) {
  const impact = impactOf(domain.id, registry);
  const children = getChildren(domain.id, registry);
  const node = graph.get(domain.id);
  const lockRow = LOCK.contracts?.[domain.contract?.id];

  const list = (values) => (values && values.length > 0 ? values.map((value) => `\`${value}\``).join(', ') : '_none_');

  return `${BANNER}
# ${domain.id}

> ${domain.title ?? domain.id}

| | |
| --- | --- |
| Owner | \`${domain.owner}\` |
| Kind / tier | \`${domain.kind}\` / \`${domain.tier ?? 'n/a'}\` |
| Status | \`${domain.status}\` (phase \`${domain.phase}\`) |
| Parent | ${domain.parent ? `\`${domain.parent}\`` : '_root_'} |
| Contract | ${domain.contract?.id ? `\`${domain.contract.id}\` v${domain.contract.version}` : '_none declared_'} |
| Error namespace | \`${domain.errorNamespace}\` |
| Trust | \`${domain.trust ?? 'undeclared'}\` |
| Capabilities | ${list(domain.capabilities_granted)} |
| Communication | ${list(domain.communication)} |
| Data owner | \`${domain.dataOwner ?? 'none'}\` |
| State class | \`${domain.stateOwner ?? 'undeclared'}\` |
| Failure boundary | \`${domain.failureBoundary ?? 'undeclared'}\` |

## Owns

${(domain.paths ?? []).map((path) => `- \`${path}\``).join('\n') || '_no paths_'}

## Public contract surface

${(domain.public ?? []).map((surface) => `- \`${surface}\``).join('\n') || '_none — this LEGO has no public surface yet; do not import from it._'}

## May call

${list(domain.dependsOn)}

## Must never call

${list(domain.mustNotDependOn)}

${children.length > 0 ? `## Sub-LEGOs\n\n${children.map((child) => `- \`${child.id}\``).join('\n')}\n` : ''}
## Who breaks if this changes

- Direct dependents: ${list(impact.directDependents)}
- Transitive: ${list(impact.transitiveDependents)}
- **Blast radius: ${impact.blastRadius}** (risk: ${impact.blastRadius === 0 ? 'low' : impact.blastRadius < 3 ? 'medium' : 'high'})

## Resources

${domain.resources ? Object.entries(domain.resources).map(([key, value]) => `- ${key}: \`${value}\``).join('\n') : '_undeclared_'}

## Tests that guard it

${(node.tests ?? []).map((test) => `- \`${test}\``).join('\n') || '_none declared_'}
${lockRow ? `\n## Contract lock\n\n- version \`${lockRow.version}\`${lockRow.previousVersion ? ` (was \`${lockRow.previousVersion}\`)` : ''}\n- ${lockRow.description ?? ''}\n` : ''}`;
}

/* -------------------------------------------------------------- L2 indexes */

function contractIndex(registry) {
  const rows = Object.entries(LOCK.contracts ?? {}).map(([id, row]) => {
    const owner = registry.domains.find((domain) => domain.contract?.id === id);
    return `| \`${id}\` | ${row.version} | ${row.previousVersion ?? '—'} | \`${owner?.id ?? '?'}\` | \`${owner?.owner ?? '?'}\` |`;
  });
  return `${BANNER}
# Contract index

Locked public contracts. A version here is a promise; changing it is an architecture decision.

| Contract | Version | Previous | LEGO | Owner |
| --- | --- | --- | --- | --- |
${rows.join('\n')}

## Version rules

${(LOCK.policy?.rules ?? []).map((rule) => `- ${rule}`).join('\n') || '- see contract-lock.json'}

## Compatibility semantics

- \`major\` — breaking. Needs a compatibility decision, a migration declaration, tests and controlled activation.
- \`minor\` — additive. Consumers keep working; a parent does **not** need a version bump.
- \`patch\` — behaviour-preserving fix.

Checked mechanically by \`compat.mjs\` (\`classifyChange\`, \`satisfies\`, \`planUpgrade\`, \`canReplaceImplementation\`) and gate rule R9.
`;
}

function capabilityIndex(registry) {
  const byCapability = new Map();
  for (const domain of registry.domains) {
    for (const capability of domain.capabilities ?? []) {
      const key = typeof capability === 'string' ? capability : capability.id;
      if (!byCapability.has(key)) byCapability.set(key, []);
      byCapability.get(key).push(domain.id);
    }
  }
  const rows = [...byCapability.entries()].sort().map(([capability, owners]) => `| \`${capability}\` | ${owners.map((owner) => `\`${owner}\``).join(', ')} |`);

  const trustRows = Object.entries(FOUNDATION.trust.levels).map(
    ([level, meta]) => `| \`${level}\` | ${meta.rank} | ${(FOUNDATION.trust.defaultGrants[level] ?? []).map((grant) => `\`${grant}\``).join(', ') || '_none_'} | ${meta.summary} |`,
  );

  return `${BANNER}
# Capability index

## Declared feature capabilities

| Capability | Provided by |
| --- | --- |
${rows.join('\n')}

## Security capabilities and trust

Trust and capability are **separate axes**. A trust level does not imply a capability; capabilities are granted deliberately.

| Trust | Rank | Default grants | Meaning |
| --- | --- | --- | --- |
${trustRows.join('\n')}

Security capabilities: ${FOUNDATION.trust.capabilities.map((capability) => `\`${capability}\``).join(', ')}.
`;
}

function glossary() {
  const rows = Object.entries(FOUNDATION.glossary ?? {}).map(([term, meaning]) => `| **${term}** | ${meaning} |`);
  return `${BANNER}
# Glossary

| Term | Meaning |
| --- | --- |
${rows.join('\n')}

## Communication modes

${Object.entries(FOUNDATION.communication.modes).map(([mode, meta]) => `- **${mode}** — ${meta.summary} ${meta.use ? `_Use when:_ ${meta.use}` : ''}`).join('\n')}

### Rules

${FOUNDATION.communication.rules.map((rule) => `- ${rule}`).join('\n')}
`;
}

function legoIndex(registry, graph) {
  const rows = registry.domains.map((domain) => {
    const impact = impactOf(domain.id, registry);
    return `| \`${domain.id}\` | \`${domain.owner}\` | ${domain.tier ?? '—'} | ${domain.status} | ${domain.contract?.id ? `\`${domain.contract.id}\` v${domain.contract.version}` : '—'} | ${impact.blastRadius} |`;
  });
  return `${BANNER}
# LEGO index

${registry.domains.length} LEGOs. Blast radius = how many other LEGOs a change here can reach.

| LEGO | Owner | Tier | Status | Contract | Blast radius |
| --- | --- | --- | --- | --- | --- |
${rows.join('\n')}

Full cards in \`.ai/domains/\`. Graph: \`node tools/lego/impact-graph.mjs --target <id>\`.
`;
}

function impactGraphDoc(registry, graph) {
  const rows = [...graph.values()].map(
    (node) => `| \`${node.id}\` | ${node.dependsOn.map((dep) => `\`${dep}\``).join(', ') || '—'} | ${node.dependedOnBy.map((dep) => `\`${dep}\``).join(', ') || '—'} |`,
  );
  const tiers = Object.entries(TEST_TIERS).map(([tier, meta]) => `| ${meta.cost} | \`${tier}\` | \`${meta.command}\` | ${meta.proves} |`);
  return `${BANNER}
# Impact graph and test selection

## "What depends on this?"

| LEGO | Depends on | Depended on by |
| --- | --- | --- |
${rows.join('\n')}

## Test tiers — run the cheapest that proves the change

| Cost | Tier | Command | Proves |
| --- | --- | --- | --- |
${tiers.join('\n')}

## Selection

\`\`\`
node tools/lego/impact-graph.mjs --changed <file>[,<file>...]
node tools/lego/impact-graph.mjs --plan --target <lego-id> --change "<description>"
\`\`\`

Escalation is conservative: unowned files, manifest edits, public-surface edits, dependents, blast radius >= 5 and the editor-UI compatibility path all push the tier up. When in doubt it selects \`full\`.
`;
}

function compatibilityMatrix() {
  const dimensions = NODE_CONTRACT.compatibilityMatrix.dimensions;
  return `${BANNER}
# Compatibility matrix

Every node/implementation pair is described along these dimensions:

${Object.entries(dimensions).map(([dimension, values]) => `- **${dimension}** — ${Array.isArray(values) ? values.map((value) => `\`${value}\``).join(', ') : values}`).join('\n')}

## Runtimes

${Object.entries(FOUNDATION.runtimes).map(([runtime, meta]) => `- **${runtime}** — ${meta.summary} (portability: \`${meta.portability ?? 'varies'}\`)`).join('\n')}

## Portability profiles

${FOUNDATION.portability.profiles.map((profile) => `- \`${profile}\``).join('\n')}

## Device classes

${Object.entries(FOUNDATION.deviceProfile.classes).map(([device, meta]) => `- **${device}** — ${meta.summary}`).join('\n')}

A node that cannot run on a device must say so through its portability profile. It must never fail mysteriously at runtime.
`;
}

function nodeRoutesDoc() {
  const rows = NODE_CONTRACT.creationRoutes.routes.map(
    (route) => `| \`${route.id}\` | ${route.use} | ${route.runtimes.map((runtime) => `\`${runtime}\``).join(', ')} | \`${route.portability}\` | \`${route.trust}\` | ${route.status} |`,
  );
  const rules = NODE_CONTRACT.decisionModel.rules.map((rule) => `| \`${rule.id}\` | ${rule.when} | \`${rule.prefer}\` | ${rule.because} |`);
  return `${BANNER}
# Node creation routes and the decision model

${NODE_CONTRACT.creationRoutes.routes.length} routes. All are **defined**; none is implemented in this phase.

| Route | Use when | Runtimes | Portability | Trust | Status |
| --- | --- | --- | --- | --- | --- |
${rows.join('\n')}

## Decision rules (first match wins)

| Rule | When | Prefer | Because |
| --- | --- | --- | --- |
${rules.join('\n')}

Executable: \`decideCreationRoute(facts)\` in \`src/lego/foundation.mjs\` — it returns the rule that fired, so a recommendation is always explainable.

## Rust policy

${NODE_CONTRACT.decisionModel.rustPolicy.hardConstraints.map((constraint) => `- ${constraint}`).join('\n')}

Guard: \`isRustJustified(facts)\`. Tie-break: ${NODE_CONTRACT.decisionModel.tieBreak}

## Community-node compatibility

${NODE_CONTRACT.compatibilityPromise.map((promise) => `- ${promise}`).join('\n')}
`;
}

function scaleOutDoc() {
  const manifest = JSON.parse(readFileSync(MANIFEST_FILE, 'utf8'));
  const scaleOut = manifest.scaleOut ?? {};
  return `${BANNER}
# Scale-out status — honest

> **${scaleOut.verdict ?? "The backend is NOT scale-out ready."}**

${scaleOut.principle ?? ''}

## Rules

${(scaleOut.rules ?? []).map((rule) => `- ${rule}`).join('\n')}

## Blockers

${(scaleOut.blockingForScaleOut ?? []).map((blocker) => `- **${blocker.file ?? blocker.id ?? 'blocker'}** — ${blocker.reason ?? blocker.note ?? JSON.stringify(blocker)}${blocker.owner ? ` _(owner: ${blocker.owner}, phase ${blocker.phase ?? '?'})_` : ''}`).join('\n')}

## Classification (A/B/C/D)

${scaleOut.classification ? Object.entries(scaleOut.classification.legend).map(([cls, meaning]) => `- **${cls}** — ${meaning}`).join('\n') : ''}

| Class | File | Finding | Owner | Phase |
| --- | --- | --- | --- | --- |
${(scaleOut.classification?.findings ?? []).map((finding) => `| **${finding.class}** | \`${finding.file}\` | ${finding.finding} | ${finding.owner} | ${finding.phase} |`).join('\n')}

${(scaleOut.classification?.findings ?? []).filter((finding) => finding.class === 'A').map((finding) => `### Class A blocker — \`${finding.file}\` (${finding.probe})\n\n- **Consequence:** ${finding.consequence}\n- **Owner:** ${finding.owner}, phase ${finding.phase}\n- **Contract boundary:** ${finding.boundary}\n- **Not solved here:** ${finding.notSolvedHere}`).join('\n\n')}

## Declared exceptions

${(scaleOut.exceptions ?? []).map((exception) => `- \`${exception.file ?? exception.id}\` — ${exception.reason ?? exception.note ?? ''} ${exception.status ? `(${exception.status})` : ''}`).join('\n')}

## Future contract solution

Execution-id allocation and the system of record must move behind the storage contract before any worker or multi-process deployment: local modular process -> SQLite/local -> Postgres/shared -> worker-safe execution state. The contract is what makes that swap possible without touching consumers.

Verify: \`node tools/lego/scale-out-readiness.mjs\`.
`;
}

/* ---------------------------------------------------------------- L3 recipes */

const RECIPES = {
  ADD_LEGO: {
    title: 'Add a new LEGO',
    prerequisites: ['The work does not fit an existing LEGO', 'It has a single owner and a single reason to change', 'It passes the granularity test in foundation.json'],
    steps: [
      'Add a domain entry to `src/lego/manifest/domains.json` with id, owner, kind, tier, status, phase, errorNamespace, paths, public, dependsOn, mustNotDependOn.',
      'Declare the Foundation 1.0 profile: trust, capabilities_granted, communication, dataOwner, stateOwner, failureBoundary, resources.',
      'Create the directory and a `contract/index.mjs` that exports only the public surface.',
      'If it has a public contract, add a row to `contract-lock.json` and point `contract.id` at it.',
      'Regenerate the AI pack: `npm run lego:ai`.',
    ],
    tests: ['npm run lego:arch', 'npm run lego:foundation', 'cd apps/n8n-lego && node --test test/lego-foundation.test.mjs'],
    mergeGate: 'npm run lego:gate must pass',
    rollback: 'Remove the manifest entry and the directory; the gate returns to green.',
  },
  ADD_SUB_LEGO: {
    title: 'Add a sub-LEGO inside an existing LEGO',
    prerequisites: ['Nesting depth after the change is <= 3 (deeper needs Manager approval)', 'The parent genuinely composes it rather than merely calling it'],
    steps: [
      'Add a domain entry with `parent` set to the containing LEGO.',
      'Put it under the parent path so `domainForPath` resolves it.',
      'List sibling sub-LEGOs in `mustNotDependOn` — siblings talk through the parent.',
      'If the parent depends on it, add `requires` with a version range so R9 checks compatibility.',
      'Regenerate the AI pack.',
    ],
    tests: ['npm run lego:arch:selftest', 'cd apps/n8n-lego && node --test test/lego-lifecycle.test.mjs'],
    mergeGate: 'Depth <= 3 and gate green',
    rollback: 'Remove the entry; the parent is unaffected because it only used the contract.',
  },
  UPGRADE_LEGO: {
    title: 'Upgrade a LEGO version',
    prerequisites: ['You know whether the change is major, minor or patch', '`classifyChange` agrees with you'],
    steps: [
      'Make the change.',
      'Bump `contract.version` and set `previousVersion`.',
      'Update the `contract-lock.json` row.',
      'If additive, confirm consumers\' `requires` ranges still satisfy it — a minor bump must NOT force a parent bump.',
      'If breaking, follow CHANGE_CONTRACT instead.',
    ],
    tests: ['cd apps/n8n-lego && node --test test/lego-lifecycle.test.mjs', 'npm run lego:arch'],
    mergeGate: 'R7 (contract drift) and R9 (version compatibility) green',
    rollback: 'Restore the previous version in both the manifest and the lock.',
  },
  REPLACE_IMPLEMENTATION: {
    title: 'Replace an implementation behind an unchanged contract',
    prerequisites: ['The contract does not change at all', '`canReplaceImplementation` returns true'],
    steps: [
      'Add the new implementation alongside the old one under the same contract.',
      'List it in `implementations`.',
      'Prove consumers are untouched — no consumer file may appear in the diff.',
      'Activate via the rollout model: old -> canary -> gradual -> new, with rollback.',
    ],
    tests: ['cd apps/n8n-lego && node --test test/lego-lifecycle.test.mjs', 'replay comparison old vs new where the operation is deterministic'],
    mergeGate: 'Contract version unchanged and consumer diff empty',
    rollback: 'Point the selector back at the previous implementation. No consumer change required — that is the whole point.',
  },
  MIGRATE_JS_TO_RUST: {
    title: 'Migrate a JS implementation to Rust',
    prerequisites: [
      'RUST IS CURRENTLY LOCKED — this recipe is not executable today.',
      '`isRustJustified` returns justified:true',
      'A prebuilt artifact exists for every supported platform — never a compiler on a user device',
      'The contract and the node identity (`type` + `typeVersion`) do not change',
    ],
    steps: [
      'Record an ADR with the measured benefit. "It is Rust" is not a benefit.',
      'Implement behind the existing contract as an additional implementation.',
      'Capture replay traces from the JS implementation.',
      'Replay them against Rust and compare outputs.',
      'Ship the JS implementation as the fallback, permanently.',
      'Roll out canary -> gradual with rollback armed.',
    ],
    tests: ['replay capture/replay/compare', 'full contract suite against both implementations', 'npm run lego:gate'],
    mergeGate: 'Manager approval + replay equivalence + prebuilt artifacts + JS fallback retained',
    rollback: 'Select the JS implementation. It must never be deleted.',
  },
  ADD_NODE: {
    title: 'Add a node',
    prerequisites: ['You ran the decision model', 'The node identity is new and stable'],
    steps: [
      'Run `decideCreationRoute(facts)` and record the rule that fired.',
      'Write the Node Contract descriptor: identity, manifest, parameters, io, credentials, execution, events, errors, capabilities, portability, runtimeRequirements, resources, trust.',
      'Declare the portability profile honestly — a node that needs a subprocess is not `portable`.',
      'Declare the resource profile as metadata; there is no scheduler reading it yet.',
    ],
    tests: ['npm run lego:foundation', 'contract conformance for the descriptor'],
    mergeGate: 'Descriptor complete and route recorded',
    rollback: 'Remove the descriptor; nothing else references it.',
  },
  INSTALL_NODE: {
    title: 'Install a community node',
    prerequisites: ['Trust level assigned', 'Capabilities requested explicitly'],
    steps: ['install', 'scan', 'validate against the Node Contract', 'test', 'enable'],
    tests: ['package verification', 'capability/trust conformance'],
    mergeGate: 'Scan clean and no capability granted beyond the trust level without justification',
    rollback: 'QUARANTINE_NODE.',
  },
  QUARANTINE_NODE: {
    title: 'Quarantine a misbehaving node',
    prerequisites: ['A failure was attributed to the node'],
    steps: ['disable', 'quarantine (mandatory — never delete first; the evidence matters)', 'roll back to the previous version if one exists', 'remove only after the cause is recorded'],
    tests: ['restart regression — the core must boot with the node quarantined'],
    mergeGate: 'Core unaffected by the quarantined node',
    rollback: 'Re-enable only after validation.',
  },
  CHANGE_CONTRACT: {
    title: 'Make a breaking contract change',
    prerequisites: ['There is genuinely no additive way to do it', 'Manager approval'],
    steps: [
      'Run `--plan` and read the blast radius.',
      'Record an ADR: decision, reason, alternatives, consequences.',
      'Bump the major version in the manifest and the lock.',
      'Write the migration declaration.',
      'Update every dependent listed by the impact graph.',
      'Activate in a controlled way with rollback armed.',
    ],
    tests: ['the tier selected by `--plan`', 'npm run lego:gate'],
    mergeGate: 'ADR + migration declaration + all dependents updated + gate green',
    rollback: 'Revert the major bump; dependents return to the previous range.',
  },
  RUN_IMPACT_ANALYSIS: {
    title: 'Find out what a change would break',
    prerequisites: [],
    steps: [
      '`node tools/lego/impact-graph.mjs --target <id>` — who depends on it',
      '`node tools/lego/impact-graph.mjs --plan --target <id> --change "<what>"` — the full plan',
      '`node tools/lego/impact-graph.mjs --changed <files>` — which tests to run',
    ],
    tests: ['whatever the selection returns'],
    mergeGate: 'n/a — advisory',
    rollback: 'n/a',
  },
};

function recipeDoc(id, recipe) {
  return `${BANNER}
# ${id} — ${recipe.title}

## Prerequisites

${recipe.prerequisites.length > 0 ? recipe.prerequisites.map((item) => `- ${item}`).join('\n') : '_none_'}

## Steps

${recipe.steps.map((step, index) => `${index + 1}. ${step}`).join('\n')}

## Required tests

${recipe.tests.map((test) => `- \`${test}\``).join('\n')}

## Merge gate

${recipe.mergeGate}

## Rollback condition

${recipe.rollback}
`;
}

function recipeIndex() {
  return `${BANNER}
# Recipes (SOP)

| Recipe | Use when |
| --- | --- |
${Object.entries(RECIPES).map(([id, recipe]) => `| [\`${id}\`](./recipes/${id}.md) | ${recipe.title} |`).join('\n')}

Every recipe states prerequisites, steps, required tests, merge gate and rollback condition. Follow one rather than improvising.
`;
}

function decisionCards() {
  const cards = {
    API_NODE: { question: 'A node that wraps a REST API', answer: 'declarative, or openapi-import if a spec exists', because: 'no hand-written code to maintain', avoid: 'Do not write JS for a plain REST wrapper; do not write Rust for something that is 99% network wait.' },
    CPU_HEAVY: { question: 'A hot, deterministic transform', answer: 'javascript first; rust only once measurement shows it is material', because: 'measure before you migrate', avoid: 'Do not start in Rust on a hunch. Keep the JS implementation as fallback.' },
    MOBILE: { question: 'It must run on Android/Termux', answer: 'portable JS or wasm; heavy work goes to a remote worker', because: 'no compiler and little RAM on the device', avoid: 'Never require a native build on the device. Never silently degrade — declare the portability profile.' },
    COMMUNITY_NODE: { question: 'A community node already exists', answer: 'use it, unchanged', because: 'zero implementation and zero maintenance beat any rewrite', avoid: 'Do not fork it to "clean it up". Do not change its identity.' },
    RUST_MIGRATION: { question: 'Should this become Rust?', answer: 'only if isRustJustified() passes and prebuilt artifacts exist', because: 'Rust is an implementation choice, never an architecture', avoid: 'Never mandatory, never a compiler on a user device, never a contract change, never delete the JS fallback. Currently LOCKED.' },
    REMOTE_EXECUTION: { question: 'The work is too heavy for this device', answer: 'remote worker behind the same contract', because: 'the catalog should not shrink on a small device', avoid: 'Do not introduce internal HTTP between LEGOs in the same process to "prepare" for this.' },
  };
  return `${BANNER}
# Decision cards

Six recurring decisions, pre-decided.

${Object.entries(cards).map(([id, card]) => `## ${id}

**Situation:** ${card.question}

**Do:** ${card.answer}

**Because:** ${card.because}

**Do not:** ${card.avoid}
`).join('\n')}
## Executable form

\`decideCreationRoute(facts)\` and \`isRustJustified(facts)\` in \`src/lego/foundation.mjs\` return the rule that fired, so the reasoning is auditable rather than remembered.
`;
}

function migrationCookbook() {
  return `${BANNER}
# Migration cookbook

## JS community node -> Node Contract

1. Keep the identity. \`type\` and \`typeVersion\` never change because of a migration. A workflow that referenced the node must keep working.
2. Describe the existing node as a Node Contract descriptor. Nothing about its behaviour changes.
3. Run it under the JS compatibility runtime.
4. Only later, and only with justification, add an alternative implementation behind the same contract.

## Legacy aggregate -> isolated LEGO (strangler)

1. Pick one route group in \`src/rest/routes.mjs\`.
2. Create the LEGO, declare it, give it a public contract.
3. Move the handlers; the aggregate delegates.
4. The gate's legacy-zone-growth rule (R5) guarantees the aggregate can only shrink.

## Local storage -> shared storage

Documented only; not implemented. Local JSON -> SQLite -> Postgres, behind the storage contract, with execution-id allocation moved out of the process. See \`.ai/scale-out.md\`.

## Contract v1 -> v2 (breaking)

Follow \`CHANGE_CONTRACT\`. A breaking change without a migration declaration is not mergeable.

## Rollback

Every migration must be revertible by selecting the previous implementation. If it cannot be reverted, it is not a migration — it is a rewrite, and it needs Manager approval.
`;
}

function legacyRestDoc() {
  const manifest = JSON.parse(readFileSync(MANIFEST_FILE, 'utf8'));
  const legacy = manifest.legacy ?? {};
  const owned = Object.entries(legacy.migrationTargets ?? {});
  return `${BANNER}
# Legacy REST strangler

The legacy aggregate is \`${(legacy.files ?? []).join(', ')}\`, custodian \`${legacy.custodian}\`.
It is **frozen**: it may shrink, never grow.

\`\`\`
${legacy.strangler?.path ?? ''}
\`\`\`

## Route families with an owner

| Route family | Migrates to |
| --- | --- |
${owned.map(([route, target]) => `| \`${route}\` | \`${target}\` |`).join('\n')}

## Ownership NOT resolved

These are escalated rather than assigned. Assigning a family to a convenient
domain to complete the map would be manufacturing ownership.

${(legacy.unresolvedOwnership ?? []).map((item) => `### ${item.families.join(', ')}\n\n- **Routes:** ${item.routes.map((route) => `\`${route}\``).join(', ')}\n- **Today:** ${item.currentBehaviour}\n- **Why unresolved:** ${item.why}\n- **Escalated to:** ${item.escalatedTo}\n- **Question:** ${item.question}`).join('\n\n')}

## Stub families

${legacy.stubFamilies?.note ?? ''}

${(legacy.stubFamilies?.families ?? []).map((family) => `\`${family}\``).join(', ')}

> ${legacy.stubFamilies?.rule ?? ''}

## How to carve one out

${(legacy.strangler?.carveOutProcedure ?? []).map((step) => `${step}`).join('\n')}

**Anti-pattern:** ${legacy.strangler?.antiPattern ?? ''}

## Rules

${(legacy.rules ?? []).map((rule) => `- ${rule}`).join('\n')}
`;
}

function communicationDoc() {
  return `${BANNER}
# Communication model

**The central rule: the contract does not change when the transport does.**

## The four interaction classes

| Class | Semantics | Local mechanism | Across a process |
| --- | --- | --- | --- |
| \`CALL\` | synchronous request/response — **the default** | direct function call via local dispatch | IPC / remote adapter |
| \`EVENT\` | fire-and-forget notification | lightweight in-process emitter | serialized message |
| \`STREAM\` | ordered incremental output with backpressure | async iterator | framed channel |
| \`BATCH\` | many operations in one call | grouped local call | one serialized round trip |

These are **semantics, not transports**. Nothing here is an HTTP endpoint.

## Escalation ladder — use the lightest thing that satisfies the contract

\`\`\`
same process      -> direct contract call / local dispatch
async notification -> EVENT
incremental output -> STREAM
many operations    -> BATCH
different process  -> explicit IPC / local transport adapter
remote service     -> HTTP or another explicit transport adapter
\`\`\`

No internal HTTP between local LEGOs (ADR-0004). No message bus merely because
events exist. Local calls do not serialize.

## Operation envelope

\`createEnvelope({ legoId, operation, ... })\` carries identity, correlation,
actor/scope, deadline, cancellation and idempotency. It is a frozen plain object
— cheap enough to create on every call, which is the point: an expensive
envelope would be skipped exactly where it matters.

\`deriveEnvelope(parent, spec)\` propagates correlation and **clamps the child
deadline to the parent's**, so a child can never outlive its caller.

\`serializeEnvelope()\` drops the AbortSignal at a process boundary and sets
\`cancellable: false\` — the far side must establish its own cancellation
channel rather than assume one survived the trip.

**No secrets in the envelope.** Ever.

## Cancellation

Explicit, propagating, idempotent and testable. \`throwIfCancelled(envelope)\`
is the check a long-running operation makes between units of work. A deliberate
cancellation raises \`lego.cancelled\` (not retryable); a passed deadline raises
\`lego.deadline_exceeded\` (retryable) — the distinction is the actionable part.

A cancelled parent cancels its children. A cancelled STREAM stops the producer
and runs its \`onCancel\` hook.

## Backpressure

Declaring a policy is **mandatory** for STREAM operations, because an undeclared
policy means "buffer without limit", which is how a process dies slowly.

${Object.entries({ buffer: 'queue to the high-water mark', drop: 'discard the newest', 'drop-oldest': 'discard the oldest — for live state', coalesce: 'merge pending items — for progress', block: 'await the consumer', reject: 'raise lego.backpressure', terminate: 'end the stream' }).map(([policy, meaning]) => `- \`${policy}\` — ${meaning}`).join('\n')}

## Graceful degradation

No hidden fallbacks. Every state names what the consumer should do:
\`available\`, \`degraded\`, \`capability-unavailable\`, \`optional-absent\`,
\`version-incompatible\`, \`dependency-disabled\`, \`migration-required\`,
\`feature-unsupported\`.

A version mismatch **never silently adapts**.

## Capability negotiation

\`negotiate({ consumer, capability, requires, operations })\` answers in one
call: may I access it, does it speak my version, does it have the operations I
need, is it alive right now. Failures are distinct codes — \`lego.access_denied\`
is an architecture bug, \`lego.dependency_disabled\` is an operational state,
\`lego.version_incompatible\` is a migration.

**Nesting grants nothing.** Reaching a nested LEGO requires a declaration naming
that child; being allowed to depend on its parent is not enough.

## Lifecycle

\`declared -> available -> installed -> loaded -> active -> idle -> unloaded\`,
plus \`disabled\`, \`failed\`, \`degraded\`, \`deprecated\`. Only \`active\`,
\`idle\`, \`degraded\` and \`deprecated\` are callable. Illegal transitions throw;
a rejected transition does not mutate state.
`;
}

function adrIndex() {
  const dir = join(REPO_ROOT, 'docs', 'architecture', 'adr');
  let rows = [];
  if (existsSync(dir)) {
    rows = readdirSync(dir).filter((file) => file.endsWith('.md')).sort().map((file) => {
      const first = readFileSync(join(dir, file), 'utf8').split('\n').find((line) => line.startsWith('# ')) ?? file;
      return `| [\`${file.replace('.md', '')}\`](../docs/architecture/adr/${file}) | ${first.replace(/^#\s*/, '')} |`;
    });
  }
  return `${BANNER}
# ADR index

Architecture decisions. Each records the decision, the reason, the alternatives considered, the consequences, and the date/version.

| ADR | Decision |
| --- | --- |
${rows.join('\n') || '| _none_ | |'}

New ADRs go in \`docs/architecture/adr/\` and this index regenerates.
`;
}

/* ------------------------------------------------------------------ driver */

export function generate() {
  const registry = loadRegistry({ reload: true });
  const graph = buildGraph(registry);
  const files = new Map();

  files.set('constitution.md', constitution());
  files.set('glossary.md', glossary());
  files.set('index.md', legoIndex(registry, graph));
  files.set('contracts.md', contractIndex(registry));
  files.set('capabilities.md', capabilityIndex(registry));
  files.set('decision-cards.md', decisionCards());
  files.set('recipes.md', recipeIndex());
  files.set('migration-cookbook.md', migrationCookbook());
  files.set('compatibility-matrix.md', compatibilityMatrix());
  files.set('node-routes.md', nodeRoutesDoc());
  files.set('impact-graph.md', impactGraphDoc(registry, graph));
  files.set('scale-out.md', scaleOutDoc());
  files.set('adr-index.md', adrIndex());
  files.set('communication.md', communicationDoc());
  files.set('legacy-rest.md', legacyRestDoc());

  for (const domain of registry.domains) {
    files.set(`domains/${domain.id}.md`, domainCard(domain, registry, graph));
  }
  for (const [id, recipe] of Object.entries(RECIPES)) {
    files.set(`recipes/${id}.md`, recipeDoc(id, recipe));
  }
  return files;
}

function writeAll(files) {
  if (existsSync(AI_ROOT)) rmSync(AI_ROOT, { recursive: true });
  for (const [relativePath, content] of files) {
    const absolute = join(AI_ROOT, relativePath);
    mkdirSync(dirname(absolute), { recursive: true });
    writeFileSync(absolute, content);
  }
}

function check(files) {
  const stale = [];
  for (const [relativePath, content] of files) {
    const absolute = join(AI_ROOT, relativePath);
    if (!existsSync(absolute)) stale.push(`${relativePath} (missing)`);
    else if (readFileSync(absolute, 'utf8') !== content) stale.push(`${relativePath} (out of date)`);
  }
  const expected = new Set(files.keys());
  const walk = (dir, prefix = '') => {
    if (!existsSync(dir)) return;
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const relativePath = prefix ? `${prefix}/${entry.name}` : entry.name;
      if (entry.isDirectory()) walk(join(dir, entry.name), relativePath);
      else if (!expected.has(relativePath)) stale.push(`${relativePath} (orphaned)`);
    }
  };
  walk(AI_ROOT);
  return stale;
}

const isCli = process.argv[1]?.endsWith('ai-pack.mjs');
if (isCli) {
  const files = generate();
  if (process.argv.includes('--check')) {
    const stale = check(files);
    if (stale.length === 0) {
      process.stdout.write(`OK — .ai/ is in sync with the manifest (${files.size} files).\n`);
      process.exit(0);
    }
    process.stdout.write(`.ai/ is stale — run \`npm run lego:ai\`:\n${stale.map((entry) => `  - ${entry}`).join('\n')}\n`);
    process.exit(1);
  }
  writeAll(files);
  process.stdout.write(`Generated ${files.size} file(s) into .ai/\n`);
}
