#!/usr/bin/env node
/**
 * AI architecture knowledge pack generator (P2.8-B, §40–45).
 *
 *   node tools/lego/ai-pack.mjs            # regenerate .ai/
 *   node tools/lego/ai-pack.mjs --check    # fail if .ai/ is stale (CI)
 *
 * WHY GENERATED: a hand-written `.ai/` folder is a second registry, and a second
 * registry always drifts from the first. Everything here is derived from the
 * manifest, the contract lock and the foundation vocabulary — the same data the
 * gates enforce. `--check` makes staleness a build failure, so the pack is
 * either correct or the build is red.
 *
 * CONTEXT LEVELS (§45) — an agent reads the smallest level that answers it:
 *   L0 constitution.md   always; ~40 lines
 *   L1 domains/<id>.md   one LEGO card
 *   L2 contracts.md      the contract and its version rules
 *   L3 recipes/<id>.md   a step-by-step SOP
 *   L4 the source        only when L0–L3 are insufficient
 *
 * Owner: manager. Pure Node, no dependencies.
 */
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { loadRegistry, getChildren, CONTRACT_LOCK_FILE, MANIFEST_FILE } from '../../apps/n8n-lego/src/lego/registry.mjs';
import { FOUNDATION, NODE_CONTRACT } from '../../apps/n8n-lego/src/lego/foundation.mjs';
import { buildGraph, impactOf, TEST_TIERS } from './impact-graph.mjs';

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');
const AI_ROOT = join(REPO_ROOT, '.ai');
const LOCK = JSON.parse(readFileSync(CONTRACT_LOCK_FILE, 'utf8'));

const BANNER = '<!-- GENERATED by tools/lego/ai-pack.mjs — do not edit by hand. Run `npm run lego:ai` after changing the manifest. -->';

/* ------------------------------------------------------------ L0 constitution */

function constitution() {
  return `${BANNER}
# AI Constitution — n8n LEGO backend

Ten rules. If a change violates one, it is wrong regardless of how well it works.

1. **Never reach into another LEGO's internals.** Only its public contract.
2. **Prefer the direct local call.** In-process is the default; everything else must earn its cost.
3. **No internal HTTP without a real process boundary.** Localhost HTTP between two LEGOs in the same process is pure overhead pretending to be architecture.
4. **Never break n8n editor-UI compatibility.** The wire contract is \`{data}\`, \`{count,data}\`, \`{message,code?,meta?}\`, and 501 for known-but-unimplemented.
5. **Smallest viable implementation.** The correct amount of framework is usually none.
6. **Prefer Rust only on material benefit** — high-frequency execution, real resource saving, or long-term maintainability. Never because it is Rust.
7. **WASM is for portability and sandboxing**, not for speed theatre.
8. **Never break a contract for implementation convenience.** Change the implementation; the contract is the promise.
9. **A contract change needs a version decision, a migration declaration, tests and controlled activation.** In that order.
10. **Declare, do not assume.** Capabilities, data ownership, state class, resources and trust are declared in the manifest or they do not exist.

**Universal Translation is an official AI/Agent LEGO target.** An earlier "out of scope" note
about translation is superseded: the legacy i18n ownership question is recorded as an open
decision, not as a prohibition. See \`.ai/master/TRANSLATION_PLAN.md\` (frontend consumption view)
and the frontend register \`docs/n8n-lego/decisions/cross-agent-decisions.json\` (XA-14).

## Before you change anything

\`\`\`
node tools/lego/impact-graph.mjs --plan --target <lego-id> --change "<what>"
\`\`\`

Then run the test tier it selects, then \`npm run lego:gate\`.

## Context levels — read the smallest that answers your question

| Level | File | Use it for |
| --- | --- | --- |
| L0 | \`.ai/constitution.md\` | always |
| L1 | \`.ai/domains/<id>.md\` | what one LEGO owns and may call |
| L2 | \`.ai/contracts.md\` | the contract, its version, its lock row |
| L2 | \`.ai/communication.md\` | CALL/EVENT/STREAM/BATCH, envelope, cancellation, backpressure |
| L0 | \`.ai/master/PROJECT_MASTER_PLAN.md\` | what this project is and which document is canonical |
| L1 | \`.ai/master/AI_AGENT_LEGO_MASTER_PLAN.md\` | the 15 official AI/Agent LEGO |
| L2 | \`.ai/capabilities.md\` | the operation vocabulary and surface aliases |
| L3 | \`.ai/ai-foundation.md\` | provider/runtime taxonomy, MCP boundary, zero-install |
| L3 | \`.ai/recipes/<id>.md\` | how to perform a specific change |
| L4 | the source | only when L0–L3 are insufficient |

## Current honest status

- The backend is **not scale-out ready**. See \`.ai/scale-out.md\`. Do not claim otherwise.
- Rust is **locked**. JavaScript is the active backend.
- Feature domains (Workflow, Execution, Auth, Node Registry, Storage) are **declared, not implemented**.
- The legacy REST aggregate is frozen and may only shrink — see \`.ai/legacy-rest.md\`.
- Allowances remaining: see \`.ai/index.md\`. They may shrink, never grow.
- A capability declares its operations; never infer them from a route.
- The AI Foundation is \`contract-only\` — no inference, no runtime, no MCP.
- Start at \`.ai/master/PROJECT_MASTER_PLAN.md\`; it names the canonical document for every subject.
`;
}

/* ---------------------------------------------------------------- L1 domains */

function domainCard(domain, registry, graph) {
  const impact = impactOf(domain.id, registry);
  const children = getChildren(domain.id, registry);
  const node = graph.get(domain.id);
  const lockRow = LOCK.contracts?.[domain.contract?.id];

  const list = (values) => (values && values.length > 0 ? values.map((value) => `\`${value}\``).join(', ') : '_none_');

  return `${BANNER}
# ${domain.id}

> ${domain.title ?? domain.id}

| | |
| --- | --- |
| Owner | \`${domain.owner}\` |
| Kind / tier | \`${domain.kind}\` / \`${domain.tier ?? 'n/a'}\` |
| Status | \`${domain.status}\` (phase \`${domain.phase}\`) |
| Parent | ${domain.parent ? `\`${domain.parent}\`` : '_root_'} |
| Contract | ${domain.contract?.id ? `\`${domain.contract.id}\` v${domain.contract.version}` : '_none declared_'} |
| Error namespace | \`${domain.errorNamespace}\` |
| Trust | \`${domain.trust ?? 'undeclared'}\` |
| Capabilities | ${list(domain.capabilities_granted)} |
| Communication | ${list(domain.communication)} |
| Data owner | \`${domain.dataOwner ?? 'none'}\` |
| State class | \`${domain.stateOwner ?? 'undeclared'}\` |
| Failure boundary | \`${domain.failureBoundary ?? 'undeclared'}\` |

## Owns

${(domain.paths ?? []).map((path) => `- \`${path}\``).join('\n') || '_no paths_'}

## Public contract surface

${(domain.public ?? []).map((surface) => `- \`${surface}\``).join('\n') || '_none — this LEGO has no public surface yet; do not import from it._'}

## May call

${list(domain.dependsOn)}

## Must never call

${list(domain.mustNotDependOn)}

${children.length > 0 ? `## Sub-LEGOs\n\n${children.map((child) => `- \`${child.id}\``).join('\n')}\n` : ''}
## Who breaks if this changes

- Direct dependents: ${list(impact.directDependents)}
- Transitive: ${list(impact.transitiveDependents)}
- **Blast radius: ${impact.blastRadius}** (risk: ${impact.blastRadius === 0 ? 'low' : impact.blastRadius < 3 ? 'medium' : 'high'})

## Resources

${domain.resources ? Object.entries(domain.resources).map(([key, value]) => `- ${key}: \`${value}\``).join('\n') : '_undeclared_'}

## Tests that guard it

${(node.tests ?? []).map((test) => `- \`${test}\``).join('\n') || '_none declared_'}
${lockRow ? `\n## Contract lock\n\n- version \`${lockRow.version}\`${lockRow.previousVersion ? ` (was \`${lockRow.previousVersion}\`)` : ''}\n- ${lockRow.description ?? ''}\n` : ''}`;
}

/* -------------------------------------------------------------- L2 indexes */

function contractIndex(registry) {
  const rows = Object.entries(LOCK.contracts ?? {}).map(([id, row]) => {
    const owner = registry.domains.find((domain) => domain.contract?.id === id);
    return `| \`${id}\` | ${row.version} | ${row.previousVersion ?? '—'} | \`${owner?.id ?? '?'}\` | \`${owner?.owner ?? '?'}\` |`;
  });
  return `${BANNER}
# Contract index

Locked public contracts. A version here is a promise; changing it is an architecture decision.

| Contract | Version | Previous | LEGO | Owner |
| --- | --- | --- | --- | --- |
${rows.join('\n')}

## Version rules

${(LOCK.policy?.rules ?? []).map((rule) => `- ${rule}`).join('\n') || '- see contract-lock.json'}

## Compatibility semantics

- \`major\` — breaking. Needs a compatibility decision, a migration declaration, tests and controlled activation.
- \`minor\` — additive. Consumers keep working; a parent does **not** need a version bump.
- \`patch\` — behaviour-preserving fix.

Checked mechanically by \`compat.mjs\` (\`classifyChange\`, \`satisfies\`, \`planUpgrade\`, \`canReplaceImplementation\`) and gate rule R9.
`;
}

function capabilityIndex(registry) {
  const byCapability = new Map();
  for (const domain of registry.domains) {
    for (const capability of domain.capabilities ?? []) {
      const key = typeof capability === 'string' ? capability : capability.id;
      if (!byCapability.has(key)) byCapability.set(key, []);
      byCapability.get(key).push(domain.id);
    }
  }
  const rows = [...byCapability.entries()].sort().map(([capability, owners]) => `| \`${capability}\` | ${owners.map((owner) => `\`${owner}\``).join(', ')} |`);

  // Operation vocabulary. This is the part a consumer actually negotiates
  // against, and the reason it is generated rather than written: a hand-kept
  // copy would drift from the manifest within one phase.
  const operationRows = [];
  for (const domain of registry.domains) {
    for (const capability of domain.capabilities ?? []) {
      if (typeof capability === 'string') continue;
      for (const operation of capability.operations ?? []) {
        operationRows.push(
          `| \`${capability.id}.${operation.name}\` | \`${domain.id}\` | ${operation.interaction}`
          + `${operation.backpressure ? ` (${operation.backpressure})` : ''} | \`${operation.permission}\` `
          + `| ${operation.idempotent ? 'yes' : 'no'} | ${operation.status} |`);
      }
    }
  }

  const aliasRows = (registry.surfaceAliases?.aliases ?? []).map(
    (alias) => `| \`${alias.surface}\` | \`${alias.canonical}\` | ${alias.note} |`);

  const trustRows = Object.entries(FOUNDATION.trust.levels).map(
    ([level, meta]) => `| \`${level}\` | ${meta.rank} | ${(FOUNDATION.trust.defaultGrants[level] ?? []).map((grant) => `\`${grant}\``).join(', ') || '_none_'} | ${meta.summary} |`,
  );

  return `${BANNER}
# Capability index

## Declared feature capabilities

| Capability | Provided by |
| --- | --- |
${rows.join('\n')}

## Operation vocabulary

Operations are **declared**, never inferred from route existence. A consumer reads
this table instead of guessing from a URL shape.

| Operation | LEGO | Interaction | Permission | Idempotent | Status |
| --- | --- | --- | --- | --- | --- |
${operationRows.join('\n')}

## Surface aliases

UI vocabulary is not capability identity, but the mapping must be deterministic.
An alias creates no capability, no contract and no ownership.

| Surface word | Canonical LEGO | Note |
| --- | --- | --- |
${aliasRows.join('\n')}

## Security capabilities and trust

Trust and capability are **separate axes**. A trust level does not imply a capability; capabilities are granted deliberately.

| Trust | Rank | Default grants | Meaning |
| --- | --- | --- | --- |
${trustRows.join('\n')}

Security capabilities: ${FOUNDATION.trust.capabilities.map((capability) => `\`${capability}\``).join(', ')}.
`;
}

function glossary() {
  const rows = Object.entries(FOUNDATION.glossary ?? {}).map(([term, meaning]) => `| **${term}** | ${meaning} |`);
  return `${BANNER}
# Glossary

| Term | Meaning |
| --- | --- |
${rows.join('\n')}

## Communication modes

${Object.entries(FOUNDATION.communication.modes).map(([mode, meta]) => `- **${mode}** — ${meta.summary} ${meta.use ? `_Use when:_ ${meta.use}` : ''}`).join('\n')}

### Rules

${FOUNDATION.communication.rules.map((rule) => `- ${rule}`).join('\n')}
`;
}

function legoIndex(registry, graph) {
  const rows = registry.domains.map((domain) => {
    const impact = impactOf(domain.id, registry);
    return `| \`${domain.id}\` | \`${domain.owner}\` | ${domain.tier ?? '—'} | ${domain.status} | ${domain.contract?.id ? `\`${domain.contract.id}\` v${domain.contract.version}` : '—'} | ${impact.blastRadius} |`;
  });
  return `${BANNER}
# LEGO index

${registry.domains.length} LEGOs. Blast radius = how many other LEGOs a change here can reach.

| LEGO | Owner | Tier | Status | Contract | Blast radius |
| --- | --- | --- | --- | --- | --- |
${rows.join('\n')}

Full cards in \`.ai/domains/\`. Graph: \`node tools/lego/impact-graph.mjs --target <id>\`.
`;
}

function impactGraphDoc(registry, graph) {
  const rows = [...graph.values()].map(
    (node) => `| \`${node.id}\` | ${node.dependsOn.map((dep) => `\`${dep}\``).join(', ') || '—'} | ${node.dependedOnBy.map((dep) => `\`${dep}\``).join(', ') || '—'} |`,
  );
  const tiers = Object.entries(TEST_TIERS).map(([tier, meta]) => `| ${meta.cost} | \`${tier}\` | \`${meta.command}\` | ${meta.proves} |`);
  return `${BANNER}
# Impact graph and test selection

## "What depends on this?"

| LEGO | Depends on | Depended on by |
| --- | --- | --- |
${rows.join('\n')}

## Test tiers — run the cheapest that proves the change

| Cost | Tier | Command | Proves |
| --- | --- | --- | --- |
${tiers.join('\n')}

## Selection

\`\`\`
node tools/lego/impact-graph.mjs --changed <file>[,<file>...]
node tools/lego/impact-graph.mjs --plan --target <lego-id> --change "<description>"
\`\`\`

Escalation is conservative: unowned files, manifest edits, public-surface edits, dependents, blast radius >= 5 and the editor-UI compatibility path all push the tier up. When in doubt it selects \`full\`.
`;
}

function compatibilityMatrix() {
  const dimensions = NODE_CONTRACT.compatibilityMatrix.dimensions;
  return `${BANNER}
# Compatibility matrix

Every node/implementation pair is described along these dimensions:

${Object.entries(dimensions).map(([dimension, values]) => `- **${dimension}** — ${Array.isArray(values) ? values.map((value) => `\`${value}\``).join(', ') : values}`).join('\n')}

## Runtimes

${Object.entries(FOUNDATION.runtimes).map(([runtime, meta]) => `- **${runtime}** — ${meta.summary} (portability: \`${meta.portability ?? 'varies'}\`)`).join('\n')}

## Portability profiles

${FOUNDATION.portability.profiles.map((profile) => `- \`${profile}\``).join('\n')}

## Device classes

${Object.entries(FOUNDATION.deviceProfile.classes).map(([device, meta]) => `- **${device}** — ${meta.summary}`).join('\n')}

A node that cannot run on a device must say so through its portability profile. It must never fail mysteriously at runtime.
`;
}

function nodeRoutesDoc() {
  const rows = NODE_CONTRACT.creationRoutes.routes.map(
    (route) => `| \`${route.id}\` | ${route.use} | ${route.runtimes.map((runtime) => `\`${runtime}\``).join(', ')} | \`${route.portability}\` | \`${route.trust}\` | ${route.status} |`,
  );
  const rules = NODE_CONTRACT.decisionModel.rules.map((rule) => `| \`${rule.id}\` | ${rule.when} | \`${rule.prefer}\` | ${rule.because} |`);
  return `${BANNER}
# Node creation routes and the decision model

${NODE_CONTRACT.creationRoutes.routes.length} routes. All are **defined**; none is implemented in this phase.

| Route | Use when | Runtimes | Portability | Trust | Status |
| --- | --- | --- | --- | --- | --- |
${rows.join('\n')}

## Decision rules (first match wins)

| Rule | When | Prefer | Because |
| --- | --- | --- | --- |
${rules.join('\n')}

Executable: \`decideCreationRoute(facts)\` in \`src/lego/foundation.mjs\` — it returns the rule that fired, so a recommendation is always explainable.

## Rust policy

${NODE_CONTRACT.decisionModel.rustPolicy.hardConstraints.map((constraint) => `- ${constraint}`).join('\n')}

Guard: \`isRustJustified(facts)\`. Tie-break: ${NODE_CONTRACT.decisionModel.tieBreak}

## Community-node compatibility

${NODE_CONTRACT.compatibilityPromise.map((promise) => `- ${promise}`).join('\n')}
`;
}

function scaleOutDoc() {
  const manifest = JSON.parse(readFileSync(MANIFEST_FILE, 'utf8'));
  const scaleOut = manifest.scaleOut ?? {};
  return `${BANNER}
# Scale-out status — honest

> **${scaleOut.verdict ?? "The backend is NOT scale-out ready."}**

${scaleOut.principle ?? ''}

## Rules

${(scaleOut.rules ?? []).map((rule) => `- ${rule}`).join('\n')}

## Blockers

${(scaleOut.blockingForScaleOut ?? []).map((blocker) => `- **${blocker.file ?? blocker.id ?? 'blocker'}** — ${blocker.reason ?? blocker.note ?? JSON.stringify(blocker)}${blocker.owner ? ` _(owner: ${blocker.owner}, phase ${blocker.phase ?? '?'})_` : ''}`).join('\n')}

## Classification (A/B/C/D)

${scaleOut.classification ? Object.entries(scaleOut.classification.legend).map(([cls, meaning]) => `- **${cls}** — ${meaning}`).join('\n') : ''}

| Class | File | Finding | Owner | Phase |
| --- | --- | --- | --- | --- |
${(scaleOut.classification?.findings ?? []).map((finding) => `| **${finding.class}** | \`${finding.file}\` | ${finding.finding} | ${finding.owner} | ${finding.phase} |`).join('\n')}

${(scaleOut.classification?.findings ?? []).filter((finding) => finding.class === 'A').map((finding) => `### Class A blocker — \`${finding.file}\` (${finding.probe})\n\n- **Consequence:** ${finding.consequence}\n- **Owner:** ${finding.owner}, phase ${finding.phase}\n- **Contract boundary:** ${finding.boundary}\n- **Not solved here:** ${finding.notSolvedHere}`).join('\n\n')}

## Declared exceptions

${(scaleOut.exceptions ?? []).map((exception) => `- \`${exception.file ?? exception.id}\` — ${exception.reason ?? exception.note ?? ''} ${exception.status ? `(${exception.status})` : ''}`).join('\n')}

## Future contract solution

Execution-id allocation and the system of record must move behind the storage contract before any worker or multi-process deployment: local modular process -> SQLite/local -> Postgres/shared -> worker-safe execution state. The contract is what makes that swap possible without touching consumers.

Verify: \`node tools/lego/scale-out-readiness.mjs\`.
`;
}

/* ---------------------------------------------------------------- L3 recipes */

const RECIPES = {
  ADD_LEGO: {
    title: 'Add a new LEGO',
    prerequisites: ['The work does not fit an existing LEGO', 'It has a single owner and a single reason to change', 'It passes the granularity test in foundation.json'],
    steps: [
      'Add a domain entry to `src/lego/manifest/domains.json` with id, owner, kind, tier, status, phase, errorNamespace, paths, public, dependsOn, mustNotDependOn.',
      'Declare the Foundation 1.0 profile: trust, capabilities_granted, communication, dataOwner, stateOwner, failureBoundary, resources.',
      'Create the directory and a `contract/index.mjs` that exports only the public surface.',
      'If it has a public contract, add a row to `contract-lock.json` and point `contract.id` at it.',
      'Regenerate the AI pack: `npm run lego:ai`.',
    ],
    tests: ['npm run lego:arch', 'npm run lego:foundation', 'cd apps/n8n-lego && node --test test/lego-foundation.test.mjs'],
    mergeGate: 'npm run lego:gate must pass',
    rollback: 'Remove the manifest entry and the directory; the gate returns to green.',
  },
  ADD_SUB_LEGO: {
    title: 'Add a sub-LEGO inside an existing LEGO',
    prerequisites: ['Nesting depth after the change is <= 3 (deeper needs Manager approval)', 'The parent genuinely composes it rather than merely calling it'],
    steps: [
      'Add a domain entry with `parent` set to the containing LEGO.',
      'Put it under the parent path so `domainForPath` resolves it.',
      'List sibling sub-LEGOs in `mustNotDependOn` — siblings talk through the parent.',
      'If the parent depends on it, add `requires` with a version range so R9 checks compatibility.',
      'Regenerate the AI pack.',
    ],
    tests: ['npm run lego:arch:selftest', 'cd apps/n8n-lego && node --test test/lego-lifecycle.test.mjs'],
    mergeGate: 'Depth <= 3 and gate green',
    rollback: 'Remove the entry; the parent is unaffected because it only used the contract.',
  },
  UPGRADE_LEGO: {
    title: 'Upgrade a LEGO version',
    prerequisites: ['You know whether the change is major, minor or patch', '`classifyChange` agrees with you'],
    steps: [
      'Make the change.',
      'Bump `contract.version` and set `previousVersion`.',
      'Update the `contract-lock.json` row.',
      'If additive, confirm consumers\' `requires` ranges still satisfy it — a minor bump must NOT force a parent bump.',
      'If breaking, follow CHANGE_CONTRACT instead.',
    ],
    tests: ['cd apps/n8n-lego && node --test test/lego-lifecycle.test.mjs', 'npm run lego:arch'],
    mergeGate: 'R7 (contract drift) and R9 (version compatibility) green',
    rollback: 'Restore the previous version in both the manifest and the lock.',
  },
  REPLACE_IMPLEMENTATION: {
    title: 'Replace an implementation behind an unchanged contract',
    prerequisites: ['The contract does not change at all', '`canReplaceImplementation` returns true'],
    steps: [
      'Add the new implementation alongside the old one under the same contract.',
      'List it in `implementations`.',
      'Prove consumers are untouched — no consumer file may appear in the diff.',
      'Activate via the rollout model: old -> canary -> gradual -> new, with rollback.',
    ],
    tests: ['cd apps/n8n-lego && node --test test/lego-lifecycle.test.mjs', 'replay comparison old vs new where the operation is deterministic'],
    mergeGate: 'Contract version unchanged and consumer diff empty',
    rollback: 'Point the selector back at the previous implementation. No consumer change required — that is the whole point.',
  },
  MIGRATE_JS_TO_RUST: {
    title: 'Migrate a JS implementation to Rust',
    prerequisites: [
      'RUST IS CURRENTLY LOCKED — this recipe is not executable today.',
      '`isRustJustified` returns justified:true',
      'A prebuilt artifact exists for every supported platform — never a compiler on a user device',
      'The contract and the node identity (`type` + `typeVersion`) do not change',
    ],
    steps: [
      'Record an ADR with the measured benefit. "It is Rust" is not a benefit.',
      'Implement behind the existing contract as an additional implementation.',
      'Capture replay traces from the JS implementation.',
      'Replay them against Rust and compare outputs.',
      'Ship the JS implementation as the fallback, permanently.',
      'Roll out canary -> gradual with rollback armed.',
    ],
    tests: ['replay capture/replay/compare', 'full contract suite against both implementations', 'npm run lego:gate'],
    mergeGate: 'Manager approval + replay equivalence + prebuilt artifacts + JS fallback retained',
    rollback: 'Select the JS implementation. It must never be deleted.',
  },
  ADD_NODE: {
    title: 'Add a node',
    prerequisites: ['You ran the decision model', 'The node identity is new and stable'],
    steps: [
      'Run `decideCreationRoute(facts)` and record the rule that fired.',
      'Write the Node Contract descriptor: identity, manifest, parameters, io, credentials, execution, events, errors, capabilities, portability, runtimeRequirements, resources, trust.',
      'Declare the portability profile honestly — a node that needs a subprocess is not `portable`.',
      'Declare the resource profile as metadata; there is no scheduler reading it yet.',
    ],
    tests: ['npm run lego:foundation', 'contract conformance for the descriptor'],
    mergeGate: 'Descriptor complete and route recorded',
    rollback: 'Remove the descriptor; nothing else references it.',
  },
  INSTALL_NODE: {
    title: 'Install a community node',
    prerequisites: ['Trust level assigned', 'Capabilities requested explicitly'],
    steps: ['install', 'scan', 'validate against the Node Contract', 'test', 'enable'],
    tests: ['package verification', 'capability/trust conformance'],
    mergeGate: 'Scan clean and no capability granted beyond the trust level without justification',
    rollback: 'QUARANTINE_NODE.',
  },
  QUARANTINE_NODE: {
    title: 'Quarantine a misbehaving node',
    prerequisites: ['A failure was attributed to the node'],
    steps: ['disable', 'quarantine (mandatory — never delete first; the evidence matters)', 'roll back to the previous version if one exists', 'remove only after the cause is recorded'],
    tests: ['restart regression — the core must boot with the node quarantined'],
    mergeGate: 'Core unaffected by the quarantined node',
    rollback: 'Re-enable only after validation.',
  },
  CHANGE_CONTRACT: {
    title: 'Make a breaking contract change',
    prerequisites: ['There is genuinely no additive way to do it', 'Manager approval'],
    steps: [
      'Run `--plan` and read the blast radius.',
      'Record an ADR: decision, reason, alternatives, consequences.',
      'Bump the major version in the manifest and the lock.',
      'Write the migration declaration.',
      'Update every dependent listed by the impact graph.',
      'Activate in a controlled way with rollback armed.',
    ],
    tests: ['the tier selected by `--plan`', 'npm run lego:gate'],
    mergeGate: 'ADR + migration declaration + all dependents updated + gate green',
    rollback: 'Revert the major bump; dependents return to the previous range.',
  },
  RUN_IMPACT_ANALYSIS: {
    title: 'Find out what a change would break',
    prerequisites: [],
    steps: [
      '`node tools/lego/impact-graph.mjs --target <id>` — who depends on it',
      '`node tools/lego/impact-graph.mjs --plan --target <id> --change "<what>"` — the full plan',
      '`node tools/lego/impact-graph.mjs --changed <files>` — which tests to run',
    ],
    tests: ['whatever the selection returns'],
    mergeGate: 'n/a — advisory',
    rollback: 'n/a',
  },
};

function recipeDoc(id, recipe) {
  return `${BANNER}
# ${id} — ${recipe.title}

## Prerequisites

${recipe.prerequisites.length > 0 ? recipe.prerequisites.map((item) => `- ${item}`).join('\n') : '_none_'}

## Steps

${recipe.steps.map((step, index) => `${index + 1}. ${step}`).join('\n')}

## Required tests

${recipe.tests.map((test) => `- \`${test}\``).join('\n')}

## Merge gate

${recipe.mergeGate}

## Rollback condition

${recipe.rollback}
`;
}

function recipeIndex() {
  return `${BANNER}
# Recipes (SOP)

| Recipe | Use when |
| --- | --- |
${Object.entries(RECIPES).map(([id, recipe]) => `| [\`${id}\`](./recipes/${id}.md) | ${recipe.title} |`).join('\n')}

Every recipe states prerequisites, steps, required tests, merge gate and rollback condition. Follow one rather than improvising.
`;
}

function decisionCards() {
  const cards = {
    API_NODE: { question: 'A node that wraps a REST API', answer: 'declarative, or openapi-import if a spec exists', because: 'no hand-written code to maintain', avoid: 'Do not write JS for a plain REST wrapper; do not write Rust for something that is 99% network wait.' },
    CPU_HEAVY: { question: 'A hot, deterministic transform', answer: 'javascript first; rust only once measurement shows it is material', because: 'measure before you migrate', avoid: 'Do not start in Rust on a hunch. Keep the JS implementation as fallback.' },
    MOBILE: { question: 'It must run on Android/Termux', answer: 'portable JS or wasm; heavy work goes to a remote worker', because: 'no compiler and little RAM on the device', avoid: 'Never require a native build on the device. Never silently degrade — declare the portability profile.' },
    COMMUNITY_NODE: { question: 'A community node already exists', answer: 'use it, unchanged', because: 'zero implementation and zero maintenance beat any rewrite', avoid: 'Do not fork it to "clean it up". Do not change its identity.' },
    RUST_MIGRATION: { question: 'Should this become Rust?', answer: 'only if isRustJustified() passes and prebuilt artifacts exist', because: 'Rust is an implementation choice, never an architecture', avoid: 'Never mandatory, never a compiler on a user device, never a contract change, never delete the JS fallback. Currently LOCKED.' },
    REMOTE_EXECUTION: { question: 'The work is too heavy for this device', answer: 'remote worker behind the same contract', because: 'the catalog should not shrink on a small device', avoid: 'Do not introduce internal HTTP between LEGOs in the same process to "prepare" for this.' },
  };
  return `${BANNER}
# Decision cards

Six recurring decisions, pre-decided.

${Object.entries(cards).map(([id, card]) => `## ${id}

**Situation:** ${card.question}

**Do:** ${card.answer}

**Because:** ${card.because}

**Do not:** ${card.avoid}
`).join('\n')}
## Executable form

\`decideCreationRoute(facts)\` and \`isRustJustified(facts)\` in \`src/lego/foundation.mjs\` return the rule that fired, so the reasoning is auditable rather than remembered.
`;
}

function migrationCookbook() {
  return `${BANNER}
# Migration cookbook

## JS community node -> Node Contract

1. Keep the identity. \`type\` and \`typeVersion\` never change because of a migration. A workflow that referenced the node must keep working.
2. Describe the existing node as a Node Contract descriptor. Nothing about its behaviour changes.
3. Run it under the JS compatibility runtime.
4. Only later, and only with justification, add an alternative implementation behind the same contract.

## Legacy aggregate -> isolated LEGO (strangler)

1. Pick one route group in \`src/rest/routes.mjs\`.
2. Create the LEGO, declare it, give it a public contract.
3. Move the handlers; the aggregate delegates.
4. The gate's legacy-zone-growth rule (R5) guarantees the aggregate can only shrink.

## Local storage -> shared storage

Documented only; not implemented. Local JSON -> SQLite -> Postgres, behind the storage contract, with execution-id allocation moved out of the process. See \`.ai/scale-out.md\`.

## Contract v1 -> v2 (breaking)

Follow \`CHANGE_CONTRACT\`. A breaking change without a migration declaration is not mergeable.

## Rollback

Every migration must be revertible by selecting the previous implementation. If it cannot be reverted, it is not a migration — it is a rewrite, and it needs Manager approval.
`;
}

function legacyRestDoc() {
  const manifest = JSON.parse(readFileSync(MANIFEST_FILE, 'utf8'));
  const legacy = manifest.legacy ?? {};
  const owned = Object.entries(legacy.migrationTargets ?? {});
  return `${BANNER}
# Legacy REST strangler

The legacy aggregate is \`${(legacy.files ?? []).join(', ')}\`, custodian \`${legacy.custodian}\`.
It is **frozen**: it may shrink, never grow.

\`\`\`
${legacy.strangler?.path ?? ''}
\`\`\`

## Route families with an owner

| Route family | Migrates to |
| --- | --- |
${owned.map(([route, target]) => `| \`${route}\` | \`${target}\` |`).join('\n')}

## Ownership NOT resolved

These are escalated rather than assigned. Assigning a family to a convenient
domain to complete the map would be manufacturing ownership.

${(legacy.unresolvedOwnership ?? []).map((item) => `### ${item.families.join(', ')}\n\n- **Routes:** ${item.routes.map((route) => `\`${route}\``).join(', ')}\n- **Today:** ${item.currentBehaviour}\n- **Why unresolved:** ${item.why}\n- **Escalated to:** ${item.escalatedTo}\n- **Question:** ${item.question}`).join('\n\n')}

## Stub families

${legacy.stubFamilies?.note ?? ''}

${(legacy.stubFamilies?.families ?? []).map((family) => `\`${family}\``).join(', ')}

> ${legacy.stubFamilies?.rule ?? ''}

## How to carve one out

${(legacy.strangler?.carveOutProcedure ?? []).map((step) => `${step}`).join('\n')}

**Anti-pattern:** ${legacy.strangler?.antiPattern ?? ''}

## Rules

${(legacy.rules ?? []).map((rule) => `- ${rule}`).join('\n')}
`;
}

function communicationDoc() {
  return `${BANNER}
# Communication model

**The central rule: the contract does not change when the transport does.**

## The four interaction classes

| Class | Semantics | Local mechanism | Across a process |
| --- | --- | --- | --- |
| \`CALL\` | synchronous request/response — **the default** | direct function call via local dispatch | IPC / remote adapter |
| \`EVENT\` | fire-and-forget notification | lightweight in-process emitter | serialized message |
| \`STREAM\` | ordered incremental output with backpressure | async iterator | framed channel |
| \`BATCH\` | many operations in one call | grouped local call | one serialized round trip |

These are **semantics, not transports**. Nothing here is an HTTP endpoint.

## Escalation ladder — use the lightest thing that satisfies the contract

\`\`\`
same process      -> direct contract call / local dispatch
async notification -> EVENT
incremental output -> STREAM
many operations    -> BATCH
different process  -> explicit IPC / local transport adapter
remote service     -> HTTP or another explicit transport adapter
\`\`\`

No internal HTTP between local LEGOs (ADR-0004). No message bus merely because
events exist. Local calls do not serialize.

## Operation envelope

\`createEnvelope({ legoId, operation, ... })\` carries identity, correlation,
actor/scope, deadline, cancellation and idempotency. It is a frozen plain object
— cheap enough to create on every call, which is the point: an expensive
envelope would be skipped exactly where it matters.

\`deriveEnvelope(parent, spec)\` propagates correlation and **clamps the child
deadline to the parent's**, so a child can never outlive its caller.

\`serializeEnvelope()\` drops the AbortSignal at a process boundary and sets
\`cancellable: false\` — the far side must establish its own cancellation
channel rather than assume one survived the trip.

**No secrets in the envelope.** Ever.

## Cancellation

Explicit, propagating, idempotent and testable. \`throwIfCancelled(envelope)\`
is the check a long-running operation makes between units of work. A deliberate
cancellation raises \`lego.cancelled\` (not retryable); a passed deadline raises
\`lego.deadline_exceeded\` (retryable) — the distinction is the actionable part.

A cancelled parent cancels its children. A cancelled STREAM stops the producer
and runs its \`onCancel\` hook.

## Backpressure

Declaring a policy is **mandatory** for STREAM operations, because an undeclared
policy means "buffer without limit", which is how a process dies slowly.

${Object.entries({ buffer: 'queue to the high-water mark', drop: 'discard the newest', 'drop-oldest': 'discard the oldest — for live state', coalesce: 'merge pending items — for progress', block: 'await the consumer', reject: 'raise lego.backpressure', terminate: 'end the stream' }).map(([policy, meaning]) => `- \`${policy}\` — ${meaning}`).join('\n')}

## Graceful degradation

No hidden fallbacks. Every state names what the consumer should do:
\`available\`, \`degraded\`, \`capability-unavailable\`, \`optional-absent\`,
\`version-incompatible\`, \`dependency-disabled\`, \`migration-required\`,
\`feature-unsupported\`.

A version mismatch **never silently adapts**.

## Capability negotiation

\`negotiate({ consumer, capability, requires, operations })\` answers in one
call: may I access it, does it speak my version, does it have the operations I
need, is it alive right now. Failures are distinct codes — \`lego.access_denied\`
is an architecture bug, \`lego.dependency_disabled\` is an operational state,
\`lego.version_incompatible\` is a migration.

**Nesting grants nothing.** Reaching a nested LEGO requires a declaration naming
that child; being allowed to depend on its parent is not enough.

## Lifecycle

\`declared -> available -> installed -> loaded -> active -> idle -> unloaded\`,
plus \`disabled\`, \`failed\`, \`degraded\`, \`deprecated\`. Only \`active\`,
\`idle\`, \`degraded\` and \`deprecated\` are callable. Illegal transitions throw;
a rejected transition does not mutate state.
`;
}

function aiFoundationDoc() {
  const file = join(REPO_ROOT, 'apps', 'n8n-lego', 'src', 'lego', 'manifest', 'ai-foundation.json');
  if (!existsSync(file)) return null;
  const ai = JSON.parse(readFileSync(file, 'utf8'));
  const taxonomy = ai.taxonomy;
  return `${BANNER}
# AI Foundation — contracts only

> **Status: \`${ai.status}\`.** ${ai.notImplemented.join(' ')}

## The five concepts, kept separate

Conflating any two of these is what makes an integration unreplaceable.

${Object.entries(taxonomy.concepts).map(([name, meaning]) => `- **${name}** — ${meaning}`).join('\n')}

\`\`\`
${taxonomy.layering}
\`\`\`

**Anti-pattern:** ${taxonomy.antiPattern}

## Provider kinds

| Kind | Contract | What it supplies | Examples |
| --- | --- | --- | --- |
${Object.entries(ai.providerKinds).map(([kind, value]) => `| \`${kind}\` | \`${value.contract}\` | ${value.summary} | ${value.examples.join(', ')} |`).join('\n')}

> ${ai.vendorRule}

## Operations

### \`${ai.modelGateway.contract}\`

| Operation | Interaction | Permission | Idempotent |
| --- | --- | --- | --- |
${ai.modelGateway.operations.map((op) => `| \`${op.name}\` | ${op.interaction}${op.backpressure ? ` (${op.backpressure})` : ''} | \`${op.permission}\` | ${op.idempotent} |`).join('\n')}

${ai.modelGateway.modelMetadata.rule}

### \`${ai.toolGateway.contract}\`

| Operation | Interaction | Permission | Idempotent |
| --- | --- | --- | --- |
${ai.toolGateway.operations.map((op) => `| \`${op.name}\` | ${op.interaction} | \`${op.permission}\` | ${op.idempotent} |`).join('\n')}

${ai.toolGateway.toolMetadata.rule}

### \`${ai.agentRuntime.contract}\`

| Operation | Interaction | Permission | Idempotent |
| --- | --- | --- | --- |
${ai.agentRuntime.lifecycle.map((op) => `| \`${op.name}\` | ${op.interaction}${op.backpressure ? ` (${op.backpressure})` : ''} | \`${op.permission}\` | ${op.idempotent} |`).join('\n')}

${ai.agentRuntime.runtimeMetadata.rule}

## Application providers

${ai.applicationProvider.firstClassRule}

Example decomposition for \`${ai.applicationProvider.exampleCapabilities.application}\`:

| Capability | Permission | Side effects |
| --- | --- | --- |
${ai.applicationProvider.exampleCapabilities.capabilities.map((c) => `| \`${c.id}\` | \`${c.permission}\` | ${c.sideEffects} |`).join('\n')}

## Session, delegation, events

**Session** \`${ai.agentSession.contract}\` — ${ai.agentSession.sizeRule}

States: ${ai.agentSession.states.map((s) => `\`${s}\``).join(', ')}
References: ${ai.agentSession.references.map((r) => `\`${r}\``).join(', ')}

**Delegation** \`${ai.delegation.contract}\` — ${ai.delegation.authorityRule}

${ai.delegation.budget.rule}

**Events** \`${ai.events.contract}\`

${ai.events.privacyRule}

${ai.events.types.map((t) => `\`${t}\``).join(', ')}

## Decision and approval

${ai.decision.privacyRule}

**${ai.approval.failClosedRule}**

Actions requiring approval: ${ai.approval.actionsRequiringApproval.map((a) => `\`${a}\``).join(', ')}

## Artifacts and context

${ai.artifact.storageRule}

Context scopes: ${ai.context.scopes.map((s) => `\`${s}\``).join(' > ')}

${ai.context.selectiveLoadRule}

## Resources and zero-install

| Profile | Meaning |
| --- | --- |
${Object.entries(ai.resourceProfiles.profiles).map(([name, meaning]) => `| \`${name}\` | ${meaning} |`).join('\n')}

${ai.resourceProfiles.noLocalInstallRule}

### Zero-install is a valid state

\`\`\`
${Object.entries(ai.zeroInstall.state).map(([k, v]) => `${k.padEnd(16)} ${v}`).join('\n')}
\`\`\`

Reported as: ${ai.zeroInstall.reportedAs}

> ${ai.zeroInstall.honestyRule}

## MCP boundary

\`\`\`
${ai.mcp.boundary}
\`\`\`

- ${ai.mcp.rule}
- ${ai.mcp.internalRule}
- ${ai.mcp.mappingRule}
- ${ai.mcp.exportRule}

**${ai.mcp.notBuilt}**

## Transport routing

| When | Transport | Mechanism |
| --- | --- | --- |
${ai.transportRouting.ladder.map((step) => `| ${step.when} | \`${step.transport}\` | ${step.mechanism} |`).join('\n')}

${ai.transportRouting.prohibition}

${ai.transportRouting.carryRule}

## Rust

${ai.rustPolicy.rule} ${ai.rustPolicy.prohibition}
`;
}


/* ------------------------------------------------------- master plan (P2.11) */

function readManifest(name) {
  const file = join(REPO_ROOT, 'apps', 'n8n-lego', 'src', 'lego', 'manifest', name);
  return existsSync(file) ? JSON.parse(readFileSync(file, 'utf8')) : null;
}

function readDecisions() {
  const file = join(REPO_ROOT, 'docs', 'n8n-lego', 'decisions', 'cross-agent-decisions.backend.json');
  return existsSync(file) ? JSON.parse(readFileSync(file, 'utf8')) : null;
}

const STATUS_MARK = {
  implemented: 'IMPLEMENTED',
  'contract-only': 'CONTRACT-ONLY',
  planned: 'PLANNED',
  blocked: 'BLOCKED',
  deferred: 'DEFERRED',
};

function projectMasterPlan() {
  const set = readManifest('ai-lego-set.json');
  const ai = readManifest('ai-foundation.json');
  if (!set || !ai) return null;
  const registry = loadRegistry({ reload: true });
  return `${BANNER}
# Project master plan — n8n LEGO

**Canonical for:** what this project is, which documents are authoritative, and what is true today.

## What n8n LEGO is

A contract-first reconstruction of n8n whose stable contracts live **above** the
implementation language. JavaScript is the active backend. Rust is an
implementation choice behind the same contracts, never a second architecture.

The repository is designed so that a future agent can continue from the files
alone, without conversation history. Every claim below is generated from an
authoritative declaration.

## Which document is canonical for which subject

| Subject | Canonical document | Generated from |
| --- | --- | --- |
| Project overview, status honesty | \`.ai/master/PROJECT_MASTER_PLAN.md\` | \`manifest/ai-lego-set.json\` |
| The 15 official AI/Agent LEGO | \`.ai/master/AI_AGENT_LEGO_MASTER_PLAN.md\` | \`manifest/ai-lego-set.json\` |
| Providers, runtimes, transports, MCP | \`.ai/master/AI_RUNTIME_AND_PROVIDER_PLAN.md\` | \`manifest/ai-foundation.json\` |
| Phase roadmap | \`.ai/master/IMPLEMENTATION_PHASES.md\` | \`manifest/ai-lego-set.json\` |
| Decisions and open arbitration | \`.ai/master/PROJECT_DECISIONS.md\` | ADRs + \`cross-agent-decisions.backend.json\` |
| Contract status matrix | \`.ai/master/AI_CONTRACT_MATRIX.md\` | manifests + \`contract-lock.json\` |
| The ${registry.domains.length} core domains, strangler, nesting | \`.ai/master/CORE_LEGO_ARCHITECTURE.md\` | \`manifest/domains.json\` |
| Development workflow (engineering operations, **not product architecture**) | \`.ai/master/PROJECT_WORKFORCE_ORCHESTRATION.md\` | \`manifest/project-governance.json\` |
| End-to-end scenario walkthroughs | \`.ai/master/REFERENCE_AGENT_SCENARIOS.md\` | \`manifest/reference-scenarios.json\` |
| **What is true today** | \`.ai/master/CURRENT_STATUS.md\` | all manifests |
| What is blocking progress | \`.ai/master/KNOWN_BLOCKERS.md\` | \`manifest/project-governance.json\` |
| Backend LEGO boundaries | \`.ai/index.md\`, \`.ai/domains/*\` | \`manifest/domains.json\` |
| Communication semantics | \`.ai/communication.md\` | source modules |
| Capability + operation vocabulary | \`.ai/capabilities.md\` | \`manifest/domains.json\` |
| Scale-out honesty | \`.ai/scale-out.md\` | \`manifest/domains.json\` |
| Narrative architecture | \`docs/n8n-lego/BACKEND_LEGO.md\` | hand-written prose |
| **Frontend AI architecture** | \`.ai/master/AI_UI_EXPERIENCE_MASTER_PLAN.md\` | hand-written (agent-1) |
| Frontend UI states and flows | \`.ai/master/AI_UI_STATES_AND_FLOWS.md\` | hand-written (agent-1) |
| Frontend progressive disclosure | \`.ai/master/AI_UX_PROGRESSIVE_DISCLOSURE.md\` | hand-written (agent-1) |
| Frontend accessibility and localization | \`.ai/master/AI_ACCESSIBILITY_AND_LOCALIZATION.md\` | hand-written (agent-1) |
| Frontend contract matrix | \`.ai/master/AI_FRONTEND_CONTRACT_MATRIX.md\` | hand-written (agent-1) |
| Frontend phase plan | \`.ai/master/AI_UI_IMPLEMENTATION_PHASES.md\` | hand-written (agent-1) |
| Frontend status, gates and blockers | \`.ai/master/FRONTEND_STATUS.md\` | hand-written (agent-1) |
| Platform, deployment and resource strategy | \`.ai/master/PLATFORM_AND_DEPLOYMENT_STRATEGY.md\` | hand-written |
| Frontend open decisions (XA-*) | \`docs/n8n-lego/decisions/cross-agent-decisions.json\` | hand-written (agent-1) |

Everything under \`.ai/\` **backend** space is generated. Editing it by hand is pointless — the
next \`npm run lego:ai\` overwrites it. The agent-1 frontend documents listed above are
hand-written and owned by the frontend branch; the generator preserves them and reports them
as neither generated nor orphaned. \`.ai/frontend/\`, \`.ai/cards/\`, \`.ai/index/\`, \`.ai/maps/\`
and \`.ai/README.md\` belong to that pack as well.

## Where to find the answer

A new agent should be able to answer all of these from \`.ai/master/\` alone. If
one of them cannot be answered from the listed document, that is a documentation
defect and should be reported as one.

| Question | Answered in |
| --- | --- |
| What is n8n LEGO? | \`PROJECT_MASTER_PLAN.md\` |
| What are the ${registry.domains.length} core domains? | \`CORE_LEGO_ARCHITECTURE.md\` |
| What are the 15 official AI/Agent LEGO? | \`AI_AGENT_LEGO_MASTER_PLAN.md\` |
| What is implemented vs contract-only? | \`CURRENT_STATUS.md\`, \`AI_CONTRACT_MATRIX.md\` |
| How does Assistant differ from Copilot? | \`AI_AGENT_LEGO_MASTER_PLAN.md\` (experiences) |
| What is Agent Machine? | \`AI_AGENT_LEGO_MASTER_PLAN.md\` (LEGO 3) |
| How do Skill and Capability differ? | \`AI_AGENT_LEGO_MASTER_PLAN.md\` (LEGO 2, 9) |
| How do Memory and Context differ? | \`AI_AGENT_LEGO_MASTER_PLAN.md\` (LEGO 4, 6) |
| How does the system write files? | \`AI_AGENT_LEGO_MASTER_PLAN.md\` (external action model) |
| How does MCP fit? | \`AI_RUNTIME_AND_PROVIDER_PLAN.md\` |
| How do Hermes / Claude Code / Gemini CLI fit? | \`AI_RUNTIME_AND_PROVIDER_PLAN.md\` |
| How does token accounting work? | \`REFERENCE_AGENT_SCENARIOS.md\` (context rollover) |
| How does context rollover work? | \`REFERENCE_AGENT_SCENARIOS.md\` (context rollover) |
| How does Memory Graph reach Obsidian? | \`REFERENCE_AGENT_SCENARIOS.md\` (memory/Obsidian) |
| How do permissions and approvals work? | \`AI_AGENT_LEGO_MASTER_PLAN.md\` (security invariants) |
| What is a Workspace? | \`AI_AGENT_LEGO_MASTER_PLAN.md\` (LEGO 5) |
| What is the Rust strategy? | \`PROJECT_MASTER_PLAN.md\`, ADR-0005 |
| How does the Manager/Worker system work? | \`PROJECT_WORKFORCE_ORCHESTRATION.md\` |
| What does GitHub / Supabase / the VPS gate control? | \`PROJECT_WORKFORCE_ORCHESTRATION.md\` |
| What are the current blockers? | \`KNOWN_BLOCKERS.md\` |
| What must never be done? | \`PROJECT_WORKFORCE_ORCHESTRATION.md\` (principles), \`.ai/constitution.md\` |
| What comes next? | \`IMPLEMENTATION_PHASES.md\` |
| How does AI Assistant differ from Copilot and AI Node? | \`AI_UI_EXPERIENCE_MASTER_PLAN.md\` (agent-1) |
| Which states must every AI surface render? | \`AI_UI_STATES_AND_FLOWS.md\` (agent-1) |
| What is visible at each disclosure level, and what is never rendered? | \`AI_UX_PROGRESSIVE_DISCLOSURE.md\` (agent-1) |
| How are accessibility, RTL and the six locales handled? | \`AI_ACCESSIBILITY_AND_LOCALIZATION.md\` (agent-1) |
| Which contracts do the frontend AI surfaces consume? | \`AI_FRONTEND_CONTRACT_MATRIX.md\` (agent-1) |
| When is each frontend surface built? | \`AI_UI_IMPLEMENTATION_PHASES.md\` (agent-1) |
| How does the product run on a small device, and when may Rust be used? | \`PLATFORM_AND_DEPLOYMENT_STRATEGY.md\` (agent-1) |
| What is the frontend gate status and what blocks it? | \`FRONTEND_STATUS.md\` (agent-1) |

## Backend today

| | |
| --- | --- |
| Domains registered | ${registry.domains.length} |
| Locked public contracts | ${registry.contractLock.contracts.length} |
| Declared capabilities | ${registry.domains.reduce((sum, domain) => sum + (domain.capabilities ?? []).length, 0)} |
| Published error codes | ${registry.errorContract.codes.length} |
| Temporary boundary allowances | ${registry.allowances.length} |
| Official AI/Agent LEGO | ${set.lego.length} |

## The three AI experiences

${set.experiences.rule}

${set.experiences.items.map((item) => `### ${item.id}

- **Owner:** \`${item.owner}\` · **Kind:** ${item.kind}
- **Summary:** ${item.summary}
- **Scope progression:** ${item.scopes.join(' -> ')}
${item.modes ? `- **Modes:** ${item.modes.join(', ')}\n` : ''}${item.examples ? `- **Examples:** ${item.examples.join(', ')}\n` : ''}${item.mustRespect ? `- **Must respect:** ${item.mustRespect.join(', ')}\n` : ''}${item.note ? `- **Note:** ${item.note}\n` : ''}- **Backend contracts:** ${item.backendContracts.map((c) => `\`${c}\``).join(', ')}`).join('\n\n')}

## Concept kinds — what counts as what

${Object.entries(set.conceptKinds).map(([kind, meaning]) => `- **${kind}** — ${meaning}`).join('\n')}

## Performance rules

${set.performanceRules.map((rule) => `- ${rule}`).join('\n')}

## Security invariants

${set.securityInvariants.map((rule) => `- ${rule}`).join('\n')}

## Deployment modes

| Mode | Summary | Inference |
| --- | --- | --- |
${Object.entries(set.deploymentModes).filter(([key]) => key !== 'rule').map(([key, value]) => `| \`${key}\` | ${value.summary} | ${value.inference} |`).join('\n')}

> ${set.deploymentModes.rule}

## Rust strategy

${set.rustStrategy.rule}

**Measured candidates** (n8n-controlled, hot, long-lived): ${set.rustStrategy.candidates.map((c) => `\`${c}\``).join(', ')}.
${set.rustStrategy.candidateRule}

**Never rewritten**: ${set.rustStrategy.neverRewrite.join(', ')}.
${set.rustStrategy.neverRewriteReason}

${set.rustStrategy.contractRule}

## What is NOT true today

These statements are false and must not be claimed:

${set.currentLimits.map((limit) => `- ${limit}`).join('\n')}
`;
}

function aiLegoMasterPlan() {
  const set = readManifest('ai-lego-set.json');
  if (!set) return null;
  const legoCard = (lego) => {
    const rows = [
      ['Index', `${lego.index} of 15`],
      ['Owner', `\`${lego.owner}\``],
      ['Status', `**${STATUS_MARK[lego.status] ?? lego.status}**`],
      ['Phase', lego.phase],
      ['Contracts', (lego.contracts ?? []).map((c) => `\`${c}\``).join(', ') || '_none yet_'],
      ['Versioning', lego.versioning],
      ['Depends on', (lego.dependsOn ?? []).map((d) => `\`${d}\``).join(', ') || '_nothing — leaf_'],
      ['Interaction', (lego.interaction ?? []).map((i) => `\`${i}\``).join(', ')],
      ['Permissions', (lego.permissions ?? []).map((p) => `\`${p}\``).join(', ') || '_none_'],
      ['Resource profile', `\`${lego.resourceProfile}\``],
    ];
    const extras = [];
    if (lego.definition) extras.push(`**Definition:** ${lego.definition}`);
    if (lego.distinction) extras.push(`**Distinction:** ${lego.distinction}`);
    if (lego.disclosureLevels) {
      extras.push(`**Progressive disclosure:**\n\n${Object.entries(lego.disclosureLevels).map(([level, meaning]) => `- \`${level}\` — ${meaning}`).join('\n')}\n\n> ${lego.disclosureRule}`);
    }
    if (lego.graph) {
      extras.push(`**Memory graph:**\n\n- Nodes: ${lego.graph.nodes.map((n) => `\`${n}\``).join(', ')}\n- Edges: ${lego.graph.edges.map((e) => `\`${e}\``).join(', ')}`);
    }
    if (lego.retention) extras.push(`**Retention classes:** ${lego.retention.map((r) => `\`${r}\``).join(' < ')}`);
    if (lego.loadRule) extras.push(`> ${lego.loadRule}`);
    if (lego.providerNote) extras.push(`> ${lego.providerNote}`);
    if (lego.kinds) extras.push(`**Kinds:** ${lego.kinds.map((k) => `\`${k}\``).join(', ')}`);
    if (lego.contains) extras.push(`**Contains:** ${lego.contains.join(', ')}`);
    if (lego.scopingRule) extras.push(`> ${lego.scopingRule}`);
    if (lego.scopes) extras.push(`**Scopes:** ${lego.scopes.map((s) => `\`${s}\``).join(' > ')}`);
    if (lego.continuationPackage) extras.push(`**Continuation package:** ${lego.continuationPackage.map((f) => `\`${f}\``).join(', ')}`);
    if (lego.rolloverRule) extras.push(`> ${lego.rolloverRule}`);
    if (lego.locales) extras.push(`**Planned locales:** ${lego.locales.map((l) => `\`${l}\``).join(', ')} (RTL: ${lego.rtl.join(', ')})`);
    if (lego.localeNote) extras.push(`> ${lego.localeNote}`);
    if (lego.strategies) extras.push(`**Strategies:** ${lego.strategies.map((s) => `\`${s}\``).join(', ')}`);
    if (lego.rustRule) extras.push(`> ${lego.rustRule}`);
    if (lego.registryFields) extras.push(`**Registry fields:** ${lego.registryFields.map((f) => `\`${f}\``).join(', ')}`);
    if (lego.interactionClasses) extras.push(`**Interaction classes:** ${lego.interactionClasses.map((c) => `\`${c}\``).join(', ')} — ${lego.classRule}`);
    if (lego.objects) extras.push(`**MCP objects:** ${lego.objects.map((o) => `\`${o}\``).join(', ')}`);
    if (lego.boundaryRule) extras.push(`> ${lego.boundaryRule}`);
    if (lego.internalRule) extras.push(`> ${lego.internalRule}`);
    if (lego.discoveryRule) extras.push(`> ${lego.discoveryRule}`);
    if (lego.exampleRuntimes) extras.push(`**Example runtimes:** ${lego.exampleRuntimes.join(', ')}`);
    if (lego.noRewriteRule) extras.push(`> ${lego.noRewriteRule}`);
    if (lego.graphExample) extras.push(`**Delegation graph example:** ${lego.graphExample.join(' -> ')}`);
    if (lego.authorityRule) extras.push(`> ${lego.authorityRule}`);
    if (lego.kinds === undefined && lego.metadata) extras.push(`**Metadata:** ${lego.metadata.map((m) => `\`${m}\``).join(', ')}`);
    if (lego.referenceRule) extras.push(`> ${lego.referenceRule}`);
    if (lego.requiresApproval) extras.push(`**Requires approval:** ${lego.requiresApproval.map((a) => `\`${a}\``).join(', ')}`);
    if (lego.failClosedRule) extras.push(`> ${lego.failClosedRule}`);
    if (lego.eventFields) extras.push(`**Event fields:** ${lego.eventFields.map((f) => `\`${f}\``).join(', ')} (${lego.eventCount} types)`);
    if (lego.privacyRule) extras.push(`> ${lego.privacyRule}`);
    if (lego.sources) extras.push(`**Sources:** ${lego.sources.map((s) => `\`${s}\``).join(' vs ')}`);
    if (lego.honestyRule) extras.push(`> ${lego.honestyRule}`);
    if (lego.uiRule) extras.push(`**UI rule:** ${lego.uiRule}${lego.uiOwner ? ` (${lego.uiOwner})` : ''}`);

    return `## ${lego.index}. ${lego.title}

> ${lego.mission}

| | |
| --- | --- |
${rows.map(([key, value]) => `| ${key} | ${value} |`).join('\n')}

**Scope:** ${(lego.scope ?? []).join(', ')}

**NOT in scope:** ${(lego.nonScope ?? []).join(', ')}

**Lifecycle:** ${(lego.lifecycle ?? []).map((state) => `\`${state}\``).join(' -> ')}

**Operations:** ${(lego.operations ?? []).map((op) => `\`${op}\``).join(', ') || '_none declared_'}

**Replacement boundary:** ${lego.replacementBoundary}

**Degradation:** ${(lego.degradation ?? []).map((d) => `\`${d}\``).join(', ')}

**Observability:** ${lego.observability}

**Tests:** ${(lego.tests ?? []).map((t) => `\`${t}\``).join(', ')}

**Future stages:** ${(lego.futureStages ?? []).join(' · ')}
${extras.length ? `\n${extras.join('\n\n')}\n` : ''}`;
  };

  return `${BANNER}
# AI/Agent LEGO master plan — the fifteen official LEGO

**Canonical for:** the official AI/Agent LEGO set, their boundaries and their roadmap.

> ${set.setRule}

## Status at a glance

| # | LEGO | Owner | Status | Phase |
| --- | --- | --- | --- | --- |
${set.lego.map((lego) => `| ${lego.index} | **${lego.title}** | \`${lego.owner}\` | ${STATUS_MARK[lego.status] ?? lego.status} | ${lego.phase} |`).join('\n')}

## Canonical architecture chain

\`\`\`
${set.architecture.chain.join('\n  -> ')}
\`\`\`

${set.architecture.rule}

${set.architecture.policyNote}

## Dependency graph

\`\`\`
${set.lego.map((lego) => `${lego.id.padEnd(18)} -> ${(lego.dependsOn ?? []).join(', ') || '(leaf)'}`).join('\n')}
\`\`\`

## External action model

${set.externalActionModel.rule}

| Capability | Side effects | Workspace-scoped | Approval |
| --- | --- | --- | --- |
${set.externalActionModel.examples.map((e) => `| \`${e.capability}\` | ${e.sideEffects} | ${e.workspaceScoped ? 'yes' : 'no'} | ${e.approval ?? '—'} |`).join('\n')}

**${set.externalActionModel.status}**

---

${set.lego.map(legoCard).join('\n---\n\n')}
`;
}

function aiRuntimeProviderPlan() {
  const ai = readManifest('ai-foundation.json');
  const set = readManifest('ai-lego-set.json');
  if (!ai || !set) return null;
  return `${BANNER}
# AI runtime and provider plan

**Canonical for:** provider taxonomy, runtime kinds, transport routing and the MCP boundary.

## Five concepts, never conflated

${Object.entries(ai.taxonomy.concepts).map(([name, meaning]) => `- **${name}** — ${meaning}`).join('\n')}

\`\`\`
${ai.taxonomy.layering}
\`\`\`

**Anti-pattern:** ${ai.taxonomy.antiPattern}

## Provider kinds

| Kind | Contract | Supplies | Examples |
| --- | --- | --- | --- |
${Object.entries(ai.providerKinds).map(([kind, value]) => `| \`${kind}\` | \`${value.contract}\` | ${value.summary} | ${value.examples.join(', ')} |`).join('\n')}

> ${ai.vendorRule}

### Named examples and their planes

| Example | Plane | Kind | Status |
| --- | --- | --- | --- |
| 9Router | Model plane | model gateway | not implemented |
| Composio | Tool plane | tool/app gateway | not implemented |
| GitHub | Code plane | **native** application provider | not implemented |
| Hermes / Claude Code / Gemini CLI / OpenClaw / Antigravity | Agent plane | external agent runtime | not implemented |
| MiroFish | Simulation plane | simulation runtime | not implemented |

Two rules that follow: **GitHub is never forced through Composio** — a native
application provider and a gateway-reached one are two bindings of one
capability set. And **MCP never becomes the internal business architecture**.

## Transport routing

| When | Transport | Mechanism |
| --- | --- | --- |
${ai.transportRouting.ladder.map((step) => `| ${step.when} | \`${step.transport}\` | ${step.mechanism} |`).join('\n')}

${ai.transportRouting.prohibition}

${ai.transportRouting.carryRule}

## MCP boundary

\`\`\`
${ai.mcp.boundary}
\`\`\`

- ${ai.mcp.rule}
- ${ai.mcp.internalRule}
- ${ai.mcp.mappingRule}
- ${ai.mcp.exportRule}

**${ai.mcp.notBuilt}**

## Runtime adapter lifecycle

\`\`\`
${(set.lego.find((lego) => lego.id === 'runtime-adapter')?.lifecycle ?? []).join(' -> ')}
\`\`\`

${set.lego.find((lego) => lego.id === 'runtime-adapter')?.noRewriteRule ?? ''}

## Resource profiles

| Profile | Meaning |
| --- | --- |
${Object.entries(ai.resourceProfiles.profiles).map(([name, meaning]) => `| \`${name}\` | ${meaning} |`).join('\n')}

Runtime registry tracks: ${ai.resourceProfiles.dimensions.map((d) => `\`${d}\``).join(', ')}.

${ai.resourceProfiles.noLocalInstallRule}

## Zero-install

\`\`\`
${Object.entries(ai.zeroInstall.state).map(([key, value]) => `${key.padEnd(16)} ${value}`).join('\n')}
\`\`\`

Reported as: ${ai.zeroInstall.reportedAs}

> ${ai.zeroInstall.honestyRule}
`;
}

function implementationPhases() {
  const set = readManifest('ai-lego-set.json');
  if (!set) return null;
  const phases = Object.entries(set.phases).filter(([key]) => key !== 'rule');
  return `${BANNER}
# Implementation phases

**Canonical for:** what is built when, and in what order.

> ${set.phases.rule}

| Phase | Title | Status | Delivers |
| --- | --- | --- | --- |
${phases.map(([key, value]) => `| **${key}** | ${value.title} | ${value.status} | ${value.delivers.join(', ')} |`).join('\n')}

## LEGO by phase

${phases.map(([key, value]) => {
    const members = set.lego.filter((lego) => lego.phase === key);
    return `### Phase ${key} — ${value.title} (${value.status})

${members.length === 0 ? '_No official LEGO is introduced in this phase; it delivers implementation for LEGO declared earlier._' : members.map((lego) => `- **${lego.title}** (\`${lego.owner}\`, ${STATUS_MARK[lego.status] ?? lego.status}) — ${lego.futureStages.join(' · ')}`).join('\n')}`;
  }).join('\n\n')}

## What must not happen

- No phase silently skips contract compatibility.
- No phase begins by implementing a feature domain that a prior phase only declared.
- No phase adds a vendor dependency to a provider-neutral contract.
- Phase F (measured optimisation) may not start before there is something to measure.

## Current limits

${set.currentLimits.map((limit) => `- ${limit}`).join('\n')}
`;
}

function projectDecisions() {
  const decisions = readDecisions();
  const adrDir = join(REPO_ROOT, 'docs', 'architecture', 'adr');
  const adrs = existsSync(adrDir)
    ? readdirSync(adrDir).filter((name) => name.endsWith('.md')).sort()
    : [];
  const adrRows = adrs.map((name) => {
    const first = readFileSync(join(adrDir, name), 'utf8').split('\n').find((line) => line.startsWith('# ')) ?? name;
    return `| [\`${name.replace('.md', '')}\`](../../docs/architecture/adr/${name}) | ${first.replace(/^#\s*/, '')} |`;
  });
  if (!decisions) return null;
  return `${BANNER}
# Project decisions and open arbitration

**Canonical for:** what has been decided, and what is still waiting on the manager.

## Architecture decision records

| ADR | Decision |
| --- | --- |
${adrRows.join('\n')}

## Cross-agent arbitration

Agent 1 maintains the frontend side of this record on \`${decisions.agent1Baseline.branch}\`
at \`${decisions.agent1Baseline.commit.slice(0, 8)}\`. Both sides use the same \`XA-*\` ids.

**Inspection:** ${decisions.agent1Baseline.inspected}

**Finding:** ${decisions.agent1Baseline.finding}

### Items

${decisions.items.map((item) => `#### ${item.id} — ${item.question}

- **Assigned to:** \`${item.assignedTo}\`
- **Status:** ${item.status}
${item.findingConfirmed ? `- **Finding confirmed:** ${item.findingConfirmed}\n` : ''}${item.resolution ? `- **Resolution:** ${item.resolution}\n` : ''}${item.beyondTheAsk ? `- **Beyond the ask:** ${item.beyondTheAsk}\n` : ''}${item.durability ? `- **Durability:** ${item.durability}\n` : ''}${item.backendPosition ? `- **Backend position:** ${item.backendPosition}\n` : ''}${item.whyNotResolvedHere ? `- **Why not resolved here:** ${item.whyNotResolvedHere}\n` : ''}${item.optionsForManager ? `- **Options:**\n${item.optionsForManager.map((option) => `  - ${option}`).join('\n')}\n` : ''}${item.backendRecommendation ? `- **Backend recommendation:** ${item.backendRecommendation}\n` : ''}${item.blocks ? `- **Blocks:** ${item.blocks}` : ''}`).join('\n\n')}

### New proposals raised by the backend

${decisions.newProposalsFromBackend.map((item) => `#### ${item.id} — ${item.subject}

- **Status:** ${item.status}
- **Detail:** ${item.detail}
- **Question:** ${item.question}
${item.backendReading ? `- **Backend reading:** ${item.backendReading}\n` : ''}${item.risk ? `- **Risk:** ${item.risk}\n` : ''}- **Blocks:** ${item.blocks}`).join('\n\n')}

## Alignment rules

${decisions.alignmentRules.map((rule) => `- ${rule}`).join('\n')}
`;
}

function readGovernance() {
  return readManifest('project-governance.json');
}

function readScenarios() {
  return readManifest('reference-scenarios.json');
}

/**
 * Core LEGO architecture — the 26 current domains, generated from the manifest.
 *
 * This exists because the domain count has drifted in prose before. Generating
 * it means the number is whatever the manifest says and cannot be stale.
 */
function coreLegoArchitecture() {
  const registry = loadRegistry({ reload: true });
  const manifest = JSON.parse(readFileSync(MANIFEST_FILE, 'utf8'));
  const set = readManifest('ai-lego-set.json');
  const byTier = new Map();
  for (const domain of registry.domains) {
    const tier = domain.tier ?? 'unclassified';
    if (!byTier.has(tier)) byTier.set(tier, []);
    byTier.get(tier).push(domain);
  }
  const aliasRows = (registry.surfaceAliases?.aliases ?? [])
    .map((alias) => `| \`${alias.surface}\` | \`${alias.canonical}\` | ${alias.why ?? ''} |`);

  return `${BANNER}
# Core LEGO architecture

**Canonical for:** the current core domains, the strangler boundary and the nesting rule.

The repository declares **${registry.domains.length} core LEGO domains**. That number is
generated from \`manifest/domains.json\` on every build — if a document elsewhere
states a different count, that document is stale and this one is right.

## The ${registry.domains.length} domains

| # | Domain | Owner | Tier | Status | Error namespace |
| --- | --- | --- | --- | --- | --- |
${registry.domains.map((domain, index) => `| ${index + 1} | \`${domain.id}\` | \`${domain.owner}\` | ${domain.tier ?? '—'} | ${domain.status} | \`${domain.errorNamespace ?? '—'}\` |`).join('\n')}

## By tier

${[...byTier.entries()].map(([tier, domains]) => `- **${tier}** (${domains.length}) — ${domains.map((domain) => `\`${domain.id}\``).join(', ')}`).join('\n')}

## What a LEGO must declare

Every domain declares one responsibility boundary, one owner, a public contract
and a contract version, plus capabilities, operations, permissions, interaction
classes, dependencies, forbidden dependencies, lifecycle, availability,
criticality, trust, transport, degradation, migration state, replacement
strategy, resource profile, tests and evidence.

A LEGO may be replaced internally without forcing consumers to rewrite. **The
contract is the seam** — that is the entire point of the decomposition.

## Kinds of thing

The vocabulary below is kept distinct on purpose. Most architectural confusion
in this project has come from collapsing two of these into one word.

| Kind | Meaning |
| --- | --- |
${Object.entries(set?.conceptKinds ?? {}).map(([kind, meaning]) => `| \`${kind}\` | ${meaning} |`).join('\n')}

## Strangler boundary

The legacy REST aggregate is a temporary boundary, not the future architecture:

\`\`\`
legacy REST -> compatibility boundary -> target LEGO contract -> target LEGO implementation
\`\`\`

Each carve-out picks one route family, gives the contract to the target domain,
publishes and locks it, mounts the new surface ahead of legacy routing, deletes
the legacy handler, and lets the architecture gate verify that the aggregate
actually shrank.

- Never create a "misc" domain to make ownership look complete.
- Never add new business logic to legacy.
- The legacy aggregate must shrink over time, and a gate must be able to see it.

## Nesting

${manifest.nesting.rules.map((rule) => `- ${rule}`).join('\n')}

Maximum depth: **${manifest.nesting.maxDepth}**.

## Surface aliases

${registry.surfaceAliases?.rule ?? ''}

| Surface word | Canonical domain | Why |
| --- | --- | --- |
${aliasRows.join('\n')}

> An alias creates no capability, no contract and no ownership. Ownership never
> resolves through an alias.
`;
}

/**
 * Workforce orchestration — how the project is built, as opposed to what it does.
 */
function workforceOrchestration() {
  const governance = readGovernance();
  if (!governance) return null;
  const planes = Object.entries(governance.controlPlanes).filter(([key]) => key !== 'rule');
  return `${BANNER}
# Development workflow and engineering operations

**This is NOT product architecture.** It describes how the *development* workforce and its
control planes are governed while building n8n LEGO. Nothing in this document is an n8n LEGO
domain, an AI/Agent LEGO, a runtime dependency, a product capability or a product control
plane, and no product manifest (\`domains.json\`, \`ai-lego-set.json\`, \`ai-foundation.json\`,
\`contract-lock.json\`) may reference it. Arena, the manager/worker task routing, the control
plane and the VPS gate exist to build the project; they are not part of what it builds.

**Canonical for:** how the development workforce is governed, and which control
plane owns which state.

> ${governance.twoWorldsRule}

## Two worlds

${Object.entries(governance.worlds).map(([id, world]) => `### ${id}

- **Summary:** ${world.summary}
- **Members:** ${world.members.join(', ')}
- **Governed by:** ${world.governedBy}
- **Trust:** ${world.trust}`).join('\n\n')}

## Manager authority

${governance.roles.manager.authority.map((item) => `- ${item}`).join('\n')}

## Worker authority

${governance.roles.worker.authority.map((item) => `- ${item}`).join('\n')}

### A worker may not

${governance.roles.worker.mayNot.map((item) => `- ${item}`).join('\n')}

> ${governance.roles.authorityRule}

## The worker loop

${governance.workerLoop.map((step, index) => `${index + 1}. ${step}`).join('\n')}

> ${governance.workerLoopRule}

## Job and task model

Shape: **${governance.jobTaskModel.shape}**

Task fields: ${governance.jobTaskModel.taskFields.map((field) => `\`${field}\``).join(', ')}

${governance.jobTaskModel.rules.map((rule) => `- ${rule}`).join('\n')}

**Status:** ${governance.jobTaskModel.status}

## Control planes

> ${governance.controlPlanes.rule}

${planes.map(([id, plane]) => `### ${id} — ${plane.kind}

- **Authoritative for:** ${plane.authoritativeFor.length ? plane.authoritativeFor.join(', ') : '_nothing_'}
${plane.mayNotHold ? `- **May not hold:** ${plane.mayNotHold.join(', ')}\n` : ''}${plane.mustDeclare ? `- **Must declare:** ${plane.mustDeclare.join(', ')}\n` : ''}- **Rule:** ${plane.rule}
- **Status:** ${plane.status}`).join('\n\n')}

## Permanent decision principles

${governance.decisionPrinciples.map((principle, index) => `${index + 1}. ${principle}`).join('\n')}
`;
}

/**
 * Current status + blockers. The document a new agent reads first to find out
 * what is actually true today.
 */
function currentStatus() {
  const registry = loadRegistry({ reload: true });
  const set = readManifest('ai-lego-set.json');
  const governance = readGovernance();
  const decisions = readDecisions();
  if (!set || !governance) return null;

  const capabilities = registry.domains.flatMap((domain) => domain.capabilities ?? []);
  const operations = capabilities.reduce((total, capability) => total + (capability.operations?.length ?? 0), 0);
  const counts = { implemented: 0, 'contract-only': 0, planned: 0, blocked: 0, deferred: 0 };
  for (const lego of set.lego) counts[lego.status] = (counts[lego.status] ?? 0) + 1;

  const openItems = (decisions?.items ?? []).filter((item) => /OPEN/i.test(item.status));
  const proposals = decisions?.newProposalsFromBackend ?? [];

  return `${BANNER}
# Current status

**Canonical for:** what is true in this repository right now.

Every number below is generated. If it disagrees with prose elsewhere, this
document is right and the prose is stale.

## Baselines

| | |
| --- | --- |
| Protected main baseline | \`cb71dbb201d635b15b49933764c2c2336e745809\` |
| Agent 1 branch | \`${decisions?.agent1Baseline.branch ?? '—'}\` |
| Agent 1 head (inspected, not merged) | \`${decisions?.agent1Baseline.commit ?? '—'}\` |
| Agent 2 branch | \`arena/01a0c521-n8n-rust-v-4\` |
| Current phase | ${set.phase} |

## Counts

| | |
| --- | --- |
| Core LEGO domains | **${registry.domains.length}** |
| Locked contracts | ${registry.contractLock.contracts.length} |
| Declared capabilities | ${capabilities.length} |
| Declared operations | ${operations} |
| Published error codes | ${registry.errorContract.codes.length} |
| Official AI/Agent LEGO | ${set.lego.length} |

## The ${set.lego.length} AI/Agent LEGO by status

${Object.entries(counts).filter(([, count]) => count > 0).map(([status, count]) => `- **${STATUS_MARK[status] ?? status}** — ${count}: ${set.lego.filter((lego) => lego.status === status).map((lego) => lego.title).join(', ')}`).join('\n')}

## Gates

| Gate | Command |
| --- | --- |
| Architecture | \`npm run lego:arch\` |
| Architecture selftest | \`npm run lego:arch:selftest\` |
| Foundation | \`npm run lego:foundation\` |
| Foundation selftest | \`npm run lego:foundation:selftest\` |
| Capability conformance | \`npm run lego:capabilities\` |
| Scale-out honesty | \`npm run lego:scaleout\` |
| \`.ai\` freshness | \`npm run lego:ai:check\` |
| Tests | \`npm run lego:test\` |
| All of the above | \`npm run lego:gate\` |

## What is NOT true

${set.currentLimits.map((limit) => `- ${limit}`).join('\n')}

## Scale-out readiness

**NOT READY.** ${governance.blockers.filter((blocker) => blocker.severity === 'class-A' && blocker.status === 'open').length} class-A blocker(s) remain open. See \`KNOWN_BLOCKERS.md\`.

## Open arbitration

${openItems.length + proposals.length} item(s) await the manager: ${[...openItems.map((item) => item.id), ...proposals.map((item) => item.id)].join(', ') || '_none_'}.

See \`PROJECT_DECISIONS.md\` for the full text of each.
`;
}

function knownBlockers() {
  const governance = readGovernance();
  if (!governance) return null;
  const order = { 'class-A': 0, 'class-B': 1, 'class-C': 2, governance: 3, environmental: 4 };
  const blockers = [...governance.blockers].sort((a, b) => (order[a.severity] ?? 9) - (order[b.severity] ?? 9));
  return `${BANNER}
# Known blockers

**Canonical for:** what is currently preventing progress, and who owns it.

> ${governance.blockerRule}

${blockers.map((blocker) => `## ${blocker.id} — ${blocker.title}

| | |
| --- | --- |
| Severity | **${blocker.severity}** |
| Status | **${blocker.status}** |
| Owner | \`${blocker.owner}\` |
${blocker.where ? `| Where | \`${blocker.where}\` |\n` : ''}${blocker.phase ? `| Scheduled | ${blocker.phase} |\n` : ''}${blocker.reference ? `| Reference | ${blocker.reference} |\n` : ''}
**Consequence:** ${blocker.consequence}
${blocker.resolutionBoundary ? `\n**Resolution boundary:** ${blocker.resolutionBoundary}\n` : ''}`).join('\n')}
`;
}

function referenceScenarios() {
  const scenarios = readScenarios();
  if (!scenarios) return null;
  const render = (scenario) => {
    const lines = [`## ${scenario.title}`, ''];
    if (scenario.request) lines.push(`> "${scenario.request}"`, '');
    if (scenario.steps) lines.push('**Flow:**', '', scenario.steps.map((step, index) => `${index + 1}. ${step}`).join('\n'), '');
    if (scenario.graph) {
      // Draw the elbow on the last child. A tree whose final branch is a tee
      // reads as truncated, which is the opposite of what a complete graph
      // should communicate.
      const children = scenario.graph.children;
      const drawn = children.map((child, index) => {
        const last = index === children.length - 1;
        const stem = last ? '└──' : '├──';
        const gutter = last ? '    ' : '│   ';
        const grandchildren = child === 'builder' ? (scenario.graph.builderChildren ?? []) : [];
        const nested = grandchildren.map((grandchild, position) =>
          `${gutter}${position === grandchildren.length - 1 ? '└──' : '├──'} ${grandchild}`);
        return [`${stem} ${child}`, ...nested].join('\n');
      });
      lines.push('**Agent graph:**', '', '```', scenario.graph.root, ...drawn, '```', '');
    }
    if (scenario.chain) lines.push(`**Chain:** ${scenario.chain.map((link) => `\`${link}\``).join(' -> ')}`, '');
    if (scenario.lego) lines.push(`**LEGO traversed:** ${scenario.lego.map((id) => `\`${id}\``).join(', ')}`, '');
    if (scenario.capabilities) lines.push(`**Capabilities:** ${scenario.capabilities.map((id) => `\`${id}\``).join(', ')}`, '');
    if (scenario.skills) lines.push(`**Skills:** ${scenario.skills.join(', ')}`, '');
    if (scenario.subAgents) lines.push(`**Sub-agents:** ${scenario.subAgents.join(', ')}`, '');
    if (scenario.approvalPoints) lines.push(`**Approval points:** ${scenario.approvalPoints.join('; ')}`, '');
    if (scenario.experience) lines.push(`**Experience:** \`${scenario.experience}\``, '');
    if (scenario.modeNote) lines.push(`> ${scenario.modeNote}`, '');
    if (scenario.contextProgression) lines.push(`**Context progression:** ${scenario.contextProgression.join(' -> ')}`, '');
    if (scenario.shared) lines.push(`**Shared across branches:** ${scenario.shared.join(', ')}`, '');
    if (scenario.joinRule) lines.push(`> ${scenario.joinRule}`, '');
    if (scenario.artifacts) lines.push(`**Artifacts:** ${scenario.artifacts.join(', ')}`, '');
    if (scenario.strategySelection) lines.push(`**Strategy selection:** ${scenario.strategySelection}`, '', `> ${scenario.strategyRule}`, '');
    if (scenario.externalExamples) lines.push(`**External runtimes:** ${scenario.externalExamples.join(', ')}`, '');
    if (scenario.n8nRetains) lines.push(`**n8n retains:** ${scenario.n8nRetains.join(', ')}`, '');
    if (scenario.adapterOperations) lines.push(`**Adapter operations:** ${scenario.adapterOperations.map((op) => `\`${op}\``).join(', ')}`, '');
    if (scenario.lockInRule) lines.push(`> ${scenario.lockInRule}`, '');
    if (scenario.sourceOfTruth) lines.push(`**Source of truth:** ${scenario.sourceOfTruth} · **Projection:** ${scenario.projection}`, '');
    if (scenario.retrievalRule) lines.push(`> ${scenario.retrievalRule}`, '');
    if (scenario.tokenKinds) {
      lines.push('**Token accounting:**', '', '| Kind | Meaning |', '| --- | --- |',
        ...Object.entries(scenario.tokenKinds).map(([kind, meaning]) => `| \`${kind}\` | ${meaning} |`), '');
      const example = scenario.tokenExample;
      lines.push(`Example — message **${example.message}**, model input **${example.modelInput}**, output **${example.output}**. ${example.note}`, '');
    }
    if (scenario.rolloverRule) lines.push(`> ${scenario.rolloverRule}`, '');
    if (scenario.failureRule) lines.push(`> ${scenario.failureRule}`, '');
    if (scenario.invariantsExercised) lines.push('**Invariants exercised:**', '', scenario.invariantsExercised.map((item) => `- ${item}`).join('\n'), '');
    lines.push(`**Status:** ${scenario.status}`, '');
    return lines.join('\n');
  };
  return `${BANNER}
# Reference agent scenarios

**Canonical for:** end-to-end walkthroughs proving the declared architecture can
express real requests.

> ${scenarios.purpose}

> ${scenarios.rule}

**None of these scenarios executes today.** Each is a contract walkthrough.

${scenarios.scenarios.map(render).join('\n---\n\n')}`;
}

function aiContractMatrix() {
  const set = readManifest('ai-lego-set.json');
  const ai = readManifest('ai-foundation.json');
  if (!set || !ai) return null;
  const registry = loadRegistry({ reload: true });
  const locked = new Map(registry.contractLock.contracts.map((row) => [row.id, row]));
  const declaredCapabilities = new Map();
  for (const domain of registry.domains) {
    for (const capability of domain.capabilities ?? []) declaredCapabilities.set(capability.id, { domain, capability });
  }

  const rows = [];
  for (const lego of set.lego) {
    if ((lego.contracts ?? []).length === 0) {
      rows.push(`| **${lego.title}** | _none yet_ | — | ${STATUS_MARK[lego.status]} | ${lego.versioning} | ${(lego.tests ?? []).length ? 'planned' : 'none'} |`);
      continue;
    }
    for (const contract of lego.contracts) {
      const lock = locked.get(contract);
      const capability = declaredCapabilities.get(contract);
      // A test entry is either a real path or a planned description; only
      // shorten the former, otherwise 'planned: loop, fan-out/fan-in' gets
      // sliced at the slash and reads as a different sentence.
      const tests = (lego.tests ?? [])
        .map((entry) => (entry.startsWith('test/') ? `\`${entry.split('/').pop()}\`` : entry))
        .join('; ') || 'none';
      // The lock row for the AI contracts is `ai.foundation`, which publishes
      // the module as one surface. An individual `ai.*` id is a declared
      // capability within it, not a missing lock row.
      const lockState = lock
        ? `locked @ ${lock.version}`
        : (capability ? `declared in \`${capability.domain.id}\`` : '**publicationPending**');
      rows.push(`| **${lego.title}** | \`${contract}\` | ${lockState} | ${STATUS_MARK[lego.status]} | ${lego.versioning} | ${tests} |`);
    }
  }

  const pending = set.lego.filter((lego) => String(lego.versioning).includes('publicationPending'));

  return `${BANNER}
# AI contract matrix

**Canonical for:** which AI contract exists, is locked, is declared, or is still pending publication.

## Matrix

| LEGO | Contract | Lock state | LEGO status | Versioning | Tests |
| --- | --- | --- | --- | --- | --- |
${rows.join('\n')}

## Publication pending

A \`publicationPending\` entry means the concept is declared but **no contract
version has been assigned**. No version is invented and no name is silently
changed; the owner and the decision reference are recorded instead.

${pending.length === 0 ? '_None._' : pending.map((lego) => `- **${lego.title}** (\`${lego.owner}\`) — ${lego.versioning}. Tracked for phase ${lego.phase}.`).join('\n')}

## Locked AI contracts

| Contract | Version | Owner | Status |
| --- | --- | --- | --- |
${registry.contractLock.contracts.filter((row) => row.id.startsWith('ai.')).map((row) => `| \`${row.id}\` | ${row.version} | \`${row.owner}\` | ${row.status} |`).join('\n') || '| _none_ | | | |'}

## Operation coverage

| Contract | Operations | Interaction classes |
| --- | --- | --- |
${['ai.model-gateway', 'ai.tool-gateway', 'ai.agent-runtime'].map((id) => {
    const section = [ai.modelGateway, ai.toolGateway, ai.agentRuntime].find((entry) => entry.contract === id);
    const ops = section?.operations ?? section?.lifecycle ?? [];
    return `| \`${id}\` | ${ops.length} | ${[...new Set(ops.map((op) => op.interaction))].join(', ')} |`;
  }).join('\n')}

## Honest status

${set.currentLimits.map((limit) => `- ${limit}`).join('\n')}
`;
}

function adrIndex() {
  const dir = join(REPO_ROOT, 'docs', 'architecture', 'adr');
  let rows = [];
  if (existsSync(dir)) {
    rows = readdirSync(dir).filter((file) => file.endsWith('.md')).sort().map((file) => {
      const first = readFileSync(join(dir, file), 'utf8').split('\n').find((line) => line.startsWith('# ')) ?? file;
      return `| [\`${file.replace('.md', '')}\`](../docs/architecture/adr/${file}) | ${first.replace(/^#\s*/, '')} |`;
    });
  }
  return `${BANNER}
# ADR index

Architecture decisions. Each records the decision, the reason, the alternatives considered, the consequences, and the date/version.

| ADR | Decision |
| --- | --- |
${rows.join('\n') || '| _none_ | |'}

New ADRs go in \`docs/architecture/adr/\` and this index regenerates.
`;
}

/* ------------------------------------------------------------------ driver */

export function generate() {
  const registry = loadRegistry({ reload: true });
  const graph = buildGraph(registry);
  const files = new Map();

  files.set('constitution.md', constitution());
  files.set('glossary.md', glossary());
  files.set('index.md', legoIndex(registry, graph));
  files.set('contracts.md', contractIndex(registry));
  files.set('capabilities.md', capabilityIndex(registry));
  files.set('decision-cards.md', decisionCards());
  files.set('recipes.md', recipeIndex());
  files.set('migration-cookbook.md', migrationCookbook());
  files.set('compatibility-matrix.md', compatibilityMatrix());
  files.set('node-routes.md', nodeRoutesDoc());
  files.set('impact-graph.md', impactGraphDoc(registry, graph));
  files.set('scale-out.md', scaleOutDoc());
  files.set('adr-index.md', adrIndex());
  files.set('communication.md', communicationDoc());
  files.set('legacy-rest.md', legacyRestDoc());
  const aiDoc = aiFoundationDoc();
  if (aiDoc) files.set('ai-foundation.md', aiDoc);
  // Master plans (P2.11) — generated so the repository remembers the
  // architecture without relying on conversation history.
  for (const [name, builder] of [
    ['PROJECT_MASTER_PLAN.md', projectMasterPlan],
    ['AI_AGENT_LEGO_MASTER_PLAN.md', aiLegoMasterPlan],
    ['AI_RUNTIME_AND_PROVIDER_PLAN.md', aiRuntimeProviderPlan],
    ['IMPLEMENTATION_PHASES.md', implementationPhases],
    ['PROJECT_DECISIONS.md', projectDecisions],
    ['AI_CONTRACT_MATRIX.md', aiContractMatrix],
    ['CORE_LEGO_ARCHITECTURE.md', coreLegoArchitecture],
    ['PROJECT_WORKFORCE_ORCHESTRATION.md', workforceOrchestration],
    ['REFERENCE_AGENT_SCENARIOS.md', referenceScenarios],
    ['CURRENT_STATUS.md', currentStatus],
    ['KNOWN_BLOCKERS.md', knownBlockers],
  ]) {
    const content = builder();
    if (content) files.set(`master/${name}`, content);
  }

  for (const domain of registry.domains) {
    files.set(`domains/${domain.id}.md`, domainCard(domain, registry, graph));
  }
  for (const [id, recipe] of Object.entries(RECIPES)) {
    files.set(`recipes/${id}.md`, recipeDoc(id, recipe));
  }
  return files;
}

/**
 * Agent-1 owns these paths inside `.ai/` (the frontend retrieval pack). This generator
 * must neither delete them nor report them as orphans: they are the frontend branch's
 * own generated/curated context, and `.ai/master/` owns the project memory they point at.
 */
const FRONTEND_OWNED = [
  'README.md',
  'frontend/',
  'cards/',
  'index/',
  'maps/',
  // Hand-written agent-1 documents that live beside the generated ones. The generated
  // PROJECT_MASTER_PLAN lists them as canonical for their subject; this generator owns the
  // other master files and must leave these alone.
  'master/FRONTEND_STATUS.md',
  'master/AI_UI_EXPERIENCE_MASTER_PLAN.md',
  'master/AI_UI_STATES_AND_FLOWS.md',
  'master/AI_UI_IMPLEMENTATION_PHASES.md',
  'master/AI_UX_PROGRESSIVE_DISCLOSURE.md',
  'master/AI_ACCESSIBILITY_AND_LOCALIZATION.md',
  'master/AI_FRONTEND_CONTRACT_MATRIX.md',
  'master/AGENT_MACHINE_PLAN.md',
  'master/CONTEXT_SESSION_MEMORY_PLAN.md',
  'master/TOKEN_USAGE_AND_RESOURCE_PLAN.md',
  'master/MEMORY_GRAPH_OBSIDIAN_PLAN.md',
  'master/SKILL_AND_CAPABILITY_PLAN.md',
  'master/WORKSPACE_AND_EXTERNAL_ACTION_PLAN.md',
  'master/MCP_AND_RUNTIME_ADAPTER_PLAN.md',
  'master/NODE_CREATOR_PLAN.md',
  'master/TRANSLATION_PLAN.md',
  'master/SECURITY_AND_APPROVAL_MODEL.md',
  'master/PLATFORM_AND_DEPLOYMENT_STRATEGY.md',
  'master/PROVIDER_TAXONOMY.md',
  'master/FRONTEND_CONSTITUTION.md',
];

function isFrontendOwned(relativePath) {
  return FRONTEND_OWNED.some((prefix) => relativePath === prefix || relativePath.startsWith(prefix));
}

function writeAll(files) {
  if (existsSync(AI_ROOT)) {
    const prune = (dir, prefix = '') => {
      for (const entry of readdirSync(dir, { withFileTypes: true })) {
        const relativePath = prefix ? `${prefix}/${entry.name}` : entry.name;
        const absolute = join(dir, entry.name);
        if (isFrontendOwned(relativePath)) continue;
        if (entry.isDirectory()) {
          prune(absolute, relativePath);
          if (readdirSync(absolute).length === 0) rmSync(absolute, { recursive: true, force: true });
        } else {
          rmSync(absolute, { force: true });
        }
      }
    };
    prune(AI_ROOT);
  }
  for (const [relativePath, content] of files) {
    const absolute = join(AI_ROOT, relativePath);
    mkdirSync(dirname(absolute), { recursive: true });
    writeFileSync(absolute, content);
  }
}

function check(files) {
  const stale = [];
  for (const [relativePath, content] of files) {
    const absolute = join(AI_ROOT, relativePath);
    if (!existsSync(absolute)) stale.push(`${relativePath} (missing)`);
    else if (readFileSync(absolute, 'utf8') !== content) stale.push(`${relativePath} (out of date)`);
  }
  const expected = new Set(files.keys());
  const walk = (dir, prefix = '') => {
    if (!existsSync(dir)) return;
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const relativePath = prefix ? `${prefix}/${entry.name}` : entry.name;
      if (isFrontendOwned(relativePath)) continue;
      if (entry.isDirectory()) walk(join(dir, entry.name), relativePath);
      else if (!expected.has(relativePath)) stale.push(`${relativePath} (orphaned)`);
    }
  };
  walk(AI_ROOT);
  return stale;
}

const isCli = process.argv[1]?.endsWith('ai-pack.mjs');
if (isCli) {
  const files = generate();
  if (process.argv.includes('--check')) {
    const stale = check(files);
    if (stale.length === 0) {
      process.stdout.write(`OK — .ai/ is in sync with the manifest (${files.size} files).\n`);
      process.exit(0);
    }
    process.stdout.write(`.ai/ is stale — run \`npm run lego:ai\`:\n${stale.map((entry) => `  - ${entry}`).join('\n')}\n`);
    process.exit(1);
  }
  writeAll(files);
  process.stdout.write(`Generated ${files.size} file(s) into .ai/\n`);
}
