"""
Canonical 49-Task Manifest Catalog for n8n-rust-v.4 (Milestones M1–M10).
Defines complete metadata for every decomposed task:
- task_key
- specialization
- milestone
- title
- description
- progress_weight
- validation_level
- dependencies
- allowed_files
- exclusive_files
- shared_read_files
- acceptance_criteria
"""

from typing import Any, Dict, List

CANONICAL_TASKS: List[Dict[str, Any]] = [
    # ==========================================================================
    # MILESTONE 1: RUNTIME KERNEL (7 tasks | 11.0 weight)
    # ==========================================================================
    {
        "task_key": "runtime-kernel/m1-runner",
        "specialization": "runtime-kernel",
        "milestone": "M1",
        "title": "Core WorkflowRunner DAG Execution Loop",
        "description": "Foundational topological workflow runner executing node sequences in order.",
        "progress_weight": 2.0,
        "validation_level": "L1",
        "dependencies": [],
        "allowed_files": ["crates/n8n-workflow/src/runtime/mod.rs", "crates/n8n-workflow/src/runtime/runner.rs"],
        "exclusive_files": ["crates/n8n-workflow/src/runtime/runner.rs"],
        "shared_read_files": ["crates/n8n-workflow/src/lib.rs"],
        "acceptance_criteria": [
            "Topological node execution preserves execution order",
            "Passes linear workflow execution tests",
        ],
    },
    {
        "task_key": "runtime-kernel/m1-frame",
        "specialization": "runtime-kernel",
        "milestone": "M1",
        "title": "Isolated ExecutionFrame & State Context",
        "description": "Structured execution frame managing memory scopes, node parameters, and outputs.",
        "progress_weight": 2.0,
        "validation_level": "L1",
        "dependencies": ["runtime-kernel/m1-runner"],
        "allowed_files": ["crates/n8n-workflow/src/runtime/frame.rs"],
        "exclusive_files": ["crates/n8n-workflow/src/runtime/frame.rs"],
        "shared_read_files": ["crates/n8n-workflow/src/runtime/runner.rs"],
        "acceptance_criteria": [
            "Frame isolates local node variables",
            "Dropping frame reclaims intermediate memory",
        ],
    },
    {
        "task_key": "runtime-kernel/m1-graph",
        "specialization": "runtime-kernel",
        "milestone": "M1",
        "title": "Runtime Execution Graph DAG Lowering",
        "description": "Converts workflow definitions into internal directed acyclic graphs for runtime dispatch.",
        "progress_weight": 2.0,
        "validation_level": "L1",
        "dependencies": ["runtime-kernel/m1-runner"],
        "allowed_files": ["crates/n8n-workflow/src/runtime/graph.rs"],
        "exclusive_files": ["crates/n8n-workflow/src/runtime/graph.rs"],
        "shared_read_files": ["crates/n8n-workflow/src/connections.rs"],
        "acceptance_criteria": [
            "DAG lowering identifies root triggers and terminal nodes",
            "Handles multi-parent convergence (diamond graphs)",
        ],
    },
    {
        "task_key": "runtime-kernel/m1-cancellation",
        "specialization": "runtime-kernel",
        "milestone": "M1",
        "title": "Thread-safe Cooperative Cancellation Token",
        "description": "Cancellation primitive allowing graceful workflow termination across worker threads.",
        "progress_weight": 1.0,
        "validation_level": "L1",
        "dependencies": ["runtime-kernel/m1-runner"],
        "allowed_files": ["crates/n8n-workflow/src/runtime/cancellation.rs"],
        "exclusive_files": ["crates/n8n-workflow/src/runtime/cancellation.rs"],
        "shared_read_files": [],
        "acceptance_criteria": [
            "Cancellation token can be triggered from external handler",
            "Runner stops executing new frames immediately when cancelled",
        ],
    },
    {
        "task_key": "runtime-kernel/m1-memory-governor",
        "specialization": "runtime-kernel",
        "milestone": "M1",
        "title": "Runtime Memory Governor Budget Integration",
        "description": "Hooks memory budget checks into the frame allocation loop.",
        "progress_weight": 2.0,
        "validation_level": "L1",
        "dependencies": ["runtime-kernel/m1-frame"],
        "allowed_files": ["crates/n8n-workflow/src/runtime/memory.rs"],
        "exclusive_files": ["crates/n8n-workflow/src/runtime/memory.rs"],
        "shared_read_files": ["crates/n8n-workflow/src/runtime/frame.rs"],
        "acceptance_criteria": [
            "Triggers backpressure at 85% budget",
            "Aborts frame creation if memory ceiling is breached",
        ],
    },
    {
        "task_key": "runtime-kernel/m1-error-propagation",
        "specialization": "runtime-kernel",
        "milestone": "M1",
        "title": "Error Routing & Propagation Pipeline",
        "description": "Structured error handling and routing to error workflows or node continuation policies.",
        "progress_weight": 1.0,
        "validation_level": "L1",
        "dependencies": ["runtime-kernel/m1-frame"],
        "allowed_files": ["crates/n8n-workflow/src/runtime/error.rs"],
        "exclusive_files": ["crates/n8n-workflow/src/runtime/error.rs"],
        "shared_read_files": [],
        "acceptance_criteria": [
            "Node errors captured cleanly without panicking",
            "Formats error output according to n8n standard schema",
        ],
    },
    {
        "task_key": "runtime-kernel/m1-lifecycle",
        "specialization": "runtime-kernel",
        "milestone": "M1",
        "title": "Workflow Execution Lifecycle Events",
        "description": "Telemetry and lifecycle hooks: on_workflow_start, on_node_start, on_workflow_finish.",
        "progress_weight": 1.0,
        "validation_level": "L1",
        "dependencies": ["runtime-kernel/m1-runner"],
        "allowed_files": ["crates/n8n-workflow/src/runtime/lifecycle.rs"],
        "exclusive_files": ["crates/n8n-workflow/src/runtime/lifecycle.rs"],
        "shared_read_files": [],
        "acceptance_criteria": [
            "Emits lifecycle events with high-resolution timestamps",
            "Tracks exact per-node duration in milliseconds",
        ],
    },

    # ==========================================================================
    # MILESTONE 2: EXECUTION ENGINE (5 tasks | 9.0 weight)
    # ==========================================================================
    {
        "task_key": "execution-engine/m2-state-machine",
        "specialization": "execution-engine",
        "milestone": "M2",
        "title": "Node State Machine Transitions",
        "description": "Finite state machine governing node states: Pending, Running, Succeeded, Failed, Skipped.",
        "progress_weight": 2.0,
        "validation_level": "L1",
        "dependencies": ["runtime-kernel/m1-runner"],
        "allowed_files": ["crates/n8n-workflow/src/runtime/executor.rs"],
        "exclusive_files": ["crates/n8n-workflow/src/runtime/executor.rs"],
        "shared_read_files": ["crates/n8n-workflow/src/runtime/frame.rs"],
        "acceptance_criteria": [
            "Rejects invalid transitions (e.g. Succeeded to Running)",
            "Terminal states are immutable",
        ],
    },
    {
        "task_key": "execution-engine/m2-scheduler",
        "specialization": "execution-engine",
        "milestone": "M2",
        "title": "Priority Task Scheduler & Dispatch Queue",
        "description": "Coordinates ready-queue nodes with worker thread pool limits.",
        "progress_weight": 2.0,
        "validation_level": "L1",
        "dependencies": ["execution-engine/m2-state-machine"],
        "allowed_files": ["crates/n8n-workflow/src/runtime/scheduler.rs"],
        "exclusive_files": ["crates/n8n-workflow/src/runtime/scheduler.rs"],
        "shared_read_files": [],
        "acceptance_criteria": [
            "Nodes wait until all incoming dependency edges succeed",
            "Enforces concurrency slots limits",
        ],
    },
    {
        "task_key": "execution-engine/m2-loop-manager",
        "specialization": "execution-engine",
        "milestone": "M2",
        "title": "LoopOverItems & Batch Iteration Manager",
        "description": "Sub-loop execution context, loop state isolation, and output array aggregation.",
        "progress_weight": 2.0,
        "validation_level": "L2",
        "dependencies": ["execution-engine/m2-scheduler"],
        "allowed_files": ["crates/n8n-workflow/src/runtime/loop_manager.rs"],
        "exclusive_files": ["crates/n8n-workflow/src/runtime/loop_manager.rs"],
        "shared_read_files": [],
        "acceptance_criteria": [
            "Maintains separate loop execution context per batch iteration",
            "Aggregates final loop outputs accurately",
        ],
    },
    {
        "task_key": "execution-engine/m2-retry-policy",
        "specialization": "execution-engine",
        "milestone": "M2",
        "title": "Node Automatic Retry Policy Engine",
        "description": "Exponential backoff retry policy for transient network or service errors.",
        "progress_weight": 1.0,
        "validation_level": "L1",
        "dependencies": ["execution-engine/m2-state-machine"],
        "allowed_files": ["crates/n8n-workflow/src/runtime/retry.rs"],
        "exclusive_files": ["crates/n8n-workflow/src/runtime/retry.rs"],
        "shared_read_files": [],
        "acceptance_criteria": [
            "Calculates exponential backoff correctly",
            "Stops retrying when maximum retry count is reached",
        ],
    },
    {
        "task_key": "execution-engine/m2-subworkflow",
        "specialization": "execution-engine",
        "milestone": "M2",
        "title": "Subworkflow Invocation Context Coordinator",
        "description": "Runs child workflows in isolated sub-execution contexts.",
        "progress_weight": 2.0,
        "validation_level": "L2",
        "dependencies": ["execution-engine/m2-scheduler"],
        "allowed_files": ["crates/n8n-workflow/src/runtime/subworkflow.rs"],
        "exclusive_files": ["crates/n8n-workflow/src/runtime/subworkflow.rs"],
        "shared_read_files": [],
        "acceptance_criteria": [
            "Child workflow parameters mapped correctly from parent",
            "Child workflow results returned cleanly to parent node",
        ],
    },

    # ==========================================================================
    # MILESTONE 3: DATA PLANE (5 tasks | 10.0 weight)
    # ==========================================================================
    {
        "task_key": "data-plane/m3-item-buffer",
        "specialization": "data-plane",
        "milestone": "M3",
        "title": "Zero-copy ItemBuffer & Record Smart Pointers",
        "description": "High-performance ItemBuffer utilizing Arc<DataRecord> to eliminate redundant payload clones.",
        "progress_weight": 3.0,
        "validation_level": "L1",
        "dependencies": [],
        "allowed_files": ["crates/n8n-execution-data/src/buffer.rs"],
        "exclusive_files": ["crates/n8n-execution-data/src/buffer.rs"],
        "shared_read_files": [],
        "acceptance_criteria": [
            "Passing item buffers across nodes requires zero JSON payload cloning",
            "Item modifications trigger copy-on-write safely",
        ],
    },
    {
        "task_key": "data-plane/m3-binary-stream",
        "specialization": "data-plane",
        "milestone": "M3",
        "title": "Chunked Binary Streaming & Spooling",
        "description": "Streaming binary data processor handling large payloads without consuming excessive heap.",
        "progress_weight": 2.0,
        "validation_level": "L1",
        "dependencies": ["data-plane/m3-item-buffer"],
        "allowed_files": ["crates/n8n-execution-data/src/binary.rs"],
        "exclusive_files": ["crates/n8n-execution-data/src/binary.rs"],
        "shared_read_files": [],
        "acceptance_criteria": [
            "Streams >50MB files in fixed 64KB chunks",
            "RAM consumption stays below 5MB during 100MB streaming",
        ],
    },
    {
        "task_key": "data-plane/m3-record-serde",
        "specialization": "data-plane",
        "milestone": "M3",
        "title": "High-throughput JSON Record Deserializer/Serializer",
        "description": "Accelerated JSON serialization maintaining strict parity with n8n JS output format.",
        "progress_weight": 2.0,
        "validation_level": "L1",
        "dependencies": ["data-plane/m3-item-buffer"],
        "allowed_files": ["crates/n8n-execution-data/src/record.rs"],
        "exclusive_files": ["crates/n8n-execution-data/src/record.rs"],
        "shared_read_files": [],
        "acceptance_criteria": [
            "Preserves boolean, integer, float, string, and null types identically",
            "100% roundtrip test parity with reference fixtures",
        ],
    },
    {
        "task_key": "data-plane/m3-item-metadata",
        "specialization": "data-plane",
        "milestone": "M3",
        "title": "Item Lineage & Paired Item Indexing",
        "description": "Maintains paired item lineage indexes across node transformations.",
        "progress_weight": 1.0,
        "validation_level": "L1",
        "dependencies": ["data-plane/m3-item-buffer"],
        "allowed_files": ["crates/n8n-execution-data/src/metadata.rs"],
        "exclusive_files": ["crates/n8n-execution-data/src/metadata.rs"],
        "shared_read_files": [],
        "acceptance_criteria": [
            "Paired item index preserved after Set and Filter transformations",
            "$item() expression resolver accurately points to source item",
        ],
    },
    {
        "task_key": "data-plane/m3-eviction",
        "specialization": "data-plane",
        "milestone": "M3",
        "title": "Intermediate Item Buffer Eviction Manager",
        "description": "Reclaims intermediate item buffers as soon as downstream consuming nodes finish execution.",
        "progress_weight": 2.0,
        "validation_level": "L1",
        "dependencies": ["data-plane/m3-item-buffer"],
        "allowed_files": ["crates/n8n-execution-data/src/eviction.rs"],
        "exclusive_files": ["crates/n8n-execution-data/src/eviction.rs"],
        "shared_read_files": [],
        "acceptance_criteria": [
            "Reclaims memory buffer when refcount hits zero",
            "Workflow memory footprint does not grow linearly with graph depth",
        ],
    },

    # ==========================================================================
    # MILESTONE 4: MEMORY MANAGEMENT (4 tasks | 8.0 weight)
    # ==========================================================================
    {
        "task_key": "memory/m4-heap-governor",
        "specialization": "memory",
        "milestone": "M4",
        "title": "Atomic Heap Allocation Tracker",
        "description": "Tracks process and workflow heap allocation against configured memory budget.",
        "progress_weight": 2.0,
        "validation_level": "L1",
        "dependencies": ["runtime-kernel/m1-memory-governor"],
        "allowed_files": ["crates/n8n-workflow/src/runtime/memory.rs"],
        "exclusive_files": ["crates/n8n-workflow/src/runtime/memory.rs"],
        "shared_read_files": [],
        "acceptance_criteria": [
            "Accurately tracks allocated memory bytes",
            "Thread-safe atomic updates without lock contention",
        ],
    },
    {
        "task_key": "memory/m4-backpressure",
        "specialization": "memory",
        "milestone": "M4",
        "title": "Dynamic Backpressure & Yield Controller",
        "description": "Applies execution micro-yields and throttles task dispatching when memory reaches 85%.",
        "progress_weight": 2.0,
        "validation_level": "L1",
        "dependencies": ["memory/m4-heap-governor"],
        "allowed_files": ["crates/n8n-workflow/src/runtime/backpressure.rs"],
        "exclusive_files": ["crates/n8n-workflow/src/runtime/backpressure.rs"],
        "shared_read_files": ["crates/n8n-workflow/src/runtime/memory.rs"],
        "acceptance_criteria": [
            "Throttles incoming task intake when memory usage exceeds 85%",
            "Resumes normal throughput when memory drops below 70%",
        ],
    },
    {
        "task_key": "memory/m4-spill-to-disk",
        "specialization": "memory",
        "milestone": "M4",
        "title": "ItemBuffer Disk Spooling Mechanism",
        "description": "Offloads cold item buffers to temporary disk files when memory reaches 90%.",
        "progress_weight": 3.0,
        "validation_level": "L2",
        "dependencies": ["memory/m4-heap-governor", "data-plane/m3-item-buffer"],
        "allowed_files": ["crates/n8n-workflow/src/runtime/spill.rs"],
        "exclusive_files": ["crates/n8n-workflow/src/runtime/spill.rs"],
        "shared_read_files": [],
        "acceptance_criteria": [
            "Spills buffers to disk without dropping data",
            "Reads back spooled records transparently upon node demand",
        ],
    },
    {
        "task_key": "memory/m4-oom-guard",
        "specialization": "memory",
        "milestone": "M4",
        "title": "Graceful OOM Abortion Guard",
        "description": "Aborts running workflow execution gracefully when memory limits are irrecoverably breached.",
        "progress_weight": 1.0,
        "validation_level": "L1",
        "dependencies": ["memory/m4-heap-governor"],
        "allowed_files": ["crates/n8n-workflow/src/runtime/oom_guard.rs"],
        "exclusive_files": ["crates/n8n-workflow/src/runtime/oom_guard.rs"],
        "shared_read_files": [],
        "acceptance_criteria": [
            "Emits MEMORY_LIMIT_EXCEEDED error",
            "Cleans up partial state and prevents OS process crash",
        ],
    },

    # ==========================================================================
    # MILESTONE 5: NODE SYSTEM (7 tasks | 12.0 weight)
    # ==========================================================================
    {
        "task_key": "node-system/m5-traits",
        "specialization": "node-system",
        "milestone": "M5",
        "title": "Standard Node Execution Traits",
        "description": "Defines core traits: INodeExecution, INodeType, and NodeExecutionContext.",
        "progress_weight": 2.0,
        "validation_level": "L1",
        "dependencies": ["data-plane/m3-item-buffer"],
        "allowed_files": ["crates/n8n-node-model/src/traits.rs", "crates/n8n-node-model/src/lib.rs"],
        "exclusive_files": ["crates/n8n-node-model/src/traits.rs"],
        "shared_read_files": [],
        "acceptance_criteria": [
            "Trait supports async execution with cancellation awareness",
            "Returns standard Result<Vec<Vec<Item>>, NodeError>",
        ],
    },
    {
        "task_key": "node-system/m5-set-node",
        "specialization": "node-system",
        "milestone": "M5",
        "title": "Native Edit Fields (Set) Node",
        "description": "Native Rust implementation of Edit Fields (Set) node for field manipulations.",
        "progress_weight": 1.0,
        "validation_level": "L1",
        "dependencies": ["node-system/m5-traits"],
        "allowed_files": ["crates/n8n-nodes-rust/src/set.rs"],
        "exclusive_files": ["crates/n8n-nodes-rust/src/set.rs"],
        "shared_read_files": [],
        "acceptance_criteria": [
            "Supports append, replace, and remove field modes",
            "Passes all set node unit tests",
        ],
    },
    {
        "task_key": "node-system/m5-if-node",
        "specialization": "node-system",
        "milestone": "M5",
        "title": "Native If / Switch Branching Node",
        "description": "Native Rust implementation of condition evaluation routing items to true/false outputs.",
        "progress_weight": 1.0,
        "validation_level": "L1",
        "dependencies": ["node-system/m5-traits"],
        "allowed_files": ["crates/n8n-nodes-rust/src/if_node.rs"],
        "exclusive_files": ["crates/n8n-nodes-rust/src/if_node.rs"],
        "shared_read_files": [],
        "acceptance_criteria": [
            "Evaluates numeric, string, and boolean comparison conditions",
            "Directs items to corresponding output slots",
        ],
    },
    {
        "task_key": "node-system/m5-code-node",
        "specialization": "node-system",
        "milestone": "M5",
        "title": "Native Code Node Execution Sandbox",
        "description": "Sandboxed JavaScript / Rust snippet execution with input/output binding.",
        "progress_weight": 3.0,
        "validation_level": "L2",
        "dependencies": ["node-system/m5-traits"],
        "allowed_files": ["crates/n8n-nodes-rust/src/code_node.rs"],
        "exclusive_files": ["crates/n8n-nodes-rust/src/code_node.rs"],
        "shared_read_files": [],
        "acceptance_criteria": [
            "Executes pure JavaScript expressions safely",
            "Reconstructs output items matching n8n JS engine format",
        ],
    },
    {
        "task_key": "node-system/m5-http-request",
        "specialization": "node-system",
        "milestone": "M5",
        "title": "Native Non-blocking HTTP Request Node",
        "description": "Async HTTP client node supporting GET, POST, headers, and authentication.",
        "progress_weight": 2.0,
        "validation_level": "L2",
        "dependencies": ["node-system/m5-traits"],
        "allowed_files": ["crates/n8n-nodes-rust/src/http_request.rs"],
        "exclusive_files": ["crates/n8n-nodes-rust/src/http_request.rs"],
        "shared_read_files": [],
        "acceptance_criteria": [
            "Asynchronously performs HTTP requests without blocking runtime thread pool",
            "Parses JSON, text, and binary responses accurately",
        ],
    },
    {
        "task_key": "node-system/m5-webhook",
        "specialization": "node-system",
        "milestone": "M5",
        "title": "Inbound Webhook Listener Adapter",
        "description": "Receives inbound webhook triggers and translates HTTP payloads into workflow items.",
        "progress_weight": 2.0,
        "validation_level": "L2",
        "dependencies": ["node-system/m5-traits"],
        "allowed_files": ["crates/n8n-nodes-rust/src/webhook.rs"],
        "exclusive_files": ["crates/n8n-nodes-rust/src/webhook.rs"],
        "shared_read_files": [],
        "acceptance_criteria": [
            "Normalizes headers, query params, and body",
            "Passes webhook request payload to workflow entry frame",
        ],
    },
    {
        "task_key": "node-system/m5-manual-trigger",
        "specialization": "node-system",
        "milestone": "M5",
        "title": "Manual Trigger Node Implementation",
        "description": "Initiates workflow execution upon manual user trigger.",
        "progress_weight": 1.0,
        "validation_level": "L1",
        "dependencies": ["node-system/m5-traits"],
        "allowed_files": ["crates/n8n-nodes-rust/src/manual_trigger.rs"],
        "exclusive_files": ["crates/n8n-nodes-rust/src/manual_trigger.rs"],
        "shared_read_files": [],
        "acceptance_criteria": [
            "Generates single item seed with execution timestamp",
            "Triggers downstream execution cleanly",
        ],
    },

    # ==========================================================================
    # MILESTONE 6: WORKFLOW MODEL (4 tasks | 6.0 weight)
    # ==========================================================================
    {
        "task_key": "workflow-model/m6-deserializer",
        "specialization": "workflow-model",
        "milestone": "M6",
        "title": "Workflow JSON Schema Deserializer",
        "description": "Parses standard n8n workflow JSON schemas into strongly-typed Rust structures.",
        "progress_weight": 2.0,
        "validation_level": "L1",
        "dependencies": [],
        "allowed_files": ["crates/n8n-workflow/src/schema.rs"],
        "exclusive_files": ["crates/n8n-workflow/src/schema.rs"],
        "shared_read_files": ["crates/n8n-workflow/src/lib.rs"],
        "acceptance_criteria": [
            "Deserializes standard v1 and v2 workflow JSON formats",
            "Gracefully handles unknown/deprecated node properties",
        ],
    },
    {
        "task_key": "workflow-model/m6-connections-inversion",
        "specialization": "workflow-model",
        "milestone": "M6",
        "title": "Connection Inversion & Adjacency Graph",
        "description": "Inverts workflow connections from source-based to destination-based lookup.",
        "progress_weight": 1.0,
        "validation_level": "L1",
        "dependencies": ["workflow-model/m6-deserializer"],
        "allowed_files": ["crates/n8n-workflow/src/connections.rs"],
        "exclusive_files": ["crates/n8n-workflow/src/connections.rs"],
        "shared_read_files": [],
        "acceptance_criteria": [
            "Inverts connections map in O(E) time",
            "Matches 100% of connections inversion unit tests",
        ],
    },
    {
        "task_key": "workflow-model/m6-parameter-resolver",
        "specialization": "workflow-model",
        "milestone": "M6",
        "title": "Node Parameter Schema & Default Hydration",
        "description": "Parses parameter definitions and hydrates missing fields with default values.",
        "progress_weight": 2.0,
        "validation_level": "L1",
        "dependencies": ["workflow-model/m6-deserializer"],
        "allowed_files": ["crates/n8n-workflow/src/parameters.rs"],
        "exclusive_files": ["crates/n8n-workflow/src/parameters.rs"],
        "shared_read_files": [],
        "acceptance_criteria": [
            "Hydrates default parameter values according to node specs",
            "Identifies raw expression strings for evaluation",
        ],
    },
    {
        "task_key": "workflow-model/m6-pinned-data",
        "specialization": "workflow-model",
        "milestone": "M6",
        "title": "Workflow Pinned Data Mock Handler",
        "description": "Intercepts node inputs when static pinned data is present in the workflow file.",
        "progress_weight": 1.0,
        "validation_level": "L1",
        "dependencies": ["workflow-model/m6-deserializer"],
        "allowed_files": ["crates/n8n-workflow/src/pinned.rs"],
        "exclusive_files": ["crates/n8n-workflow/src/pinned.rs"],
        "shared_read_files": [],
        "acceptance_criteria": [
            "Provides pinned mock items to node execution",
            "Skips executing upstream ancestors when pinned data is available",
        ],
    },

    # ==========================================================================
    # MILESTONE 7: EXPRESSION ENGINE (5 tasks | 11.0 weight)
    # ==========================================================================
    {
        "task_key": "expression-engine/m7-tokenizer",
        "specialization": "expression-engine",
        "milestone": "M7",
        "title": "Template & JavaScript Tokenizer",
        "description": "Tokenizes template expressions {{ ... }} into lexer token streams.",
        "progress_weight": 2.0,
        "validation_level": "L1",
        "dependencies": [],
        "allowed_files": ["crates/n8n-expression/src/tokenizer.rs"],
        "exclusive_files": ["crates/n8n-expression/src/tokenizer.rs"],
        "shared_read_files": ["crates/n8n-expression/src/lib.rs"],
        "acceptance_criteria": [
            "Distinguishes string literals from expression blocks",
            "Tokenizes JS operators and identifiers without allocating strings",
        ],
    },
    {
        "task_key": "expression-engine/m7-parser",
        "specialization": "expression-engine",
        "milestone": "M7",
        "title": "Expression AST Parser",
        "description": "Builds an abstract syntax tree from token streams with recursion bounds.",
        "progress_weight": 2.0,
        "validation_level": "L1",
        "dependencies": ["expression-engine/m7-tokenizer"],
        "allowed_files": ["crates/n8n-expression/src/parser.rs"],
        "exclusive_files": ["crates/n8n-expression/src/parser.rs"],
        "shared_read_files": [],
        "acceptance_criteria": [
            "Correct operator precedence (e.g. * before +)",
            "Guards against deeply nested recursion / stack exhaustion",
        ],
    },
    {
        "task_key": "expression-engine/m7-evaluator",
        "specialization": "expression-engine",
        "milestone": "M7",
        "title": "Zero-allocation AST Evaluator",
        "description": "Evaluates expression AST against runtime context values.",
        "progress_weight": 3.0,
        "validation_level": "L1",
        "dependencies": ["expression-engine/m7-parser"],
        "allowed_files": ["crates/n8n-expression/src/evaluator.rs"],
        "exclusive_files": ["crates/n8n-expression/src/evaluator.rs"],
        "shared_read_files": [],
        "acceptance_criteria": [
            "Evaluates arithmetic, logic, and member access expressions",
            "Deterministic output matching JavaScript semantics",
        ],
    },
    {
        "task_key": "expression-engine/m7-context",
        "specialization": "expression-engine",
        "milestone": "M7",
        "title": "Expression Variable Context Resolver",
        "description": "Resolves $json, $node, and $item variables from runtime frames.",
        "progress_weight": 2.0,
        "validation_level": "L1",
        "dependencies": ["expression-engine/m7-evaluator"],
        "allowed_files": ["crates/n8n-expression/src/context.rs"],
        "exclusive_files": ["crates/n8n-expression/src/context.rs"],
        "shared_read_files": [],
        "acceptance_criteria": [
            "Resolves $node['NodeName'].json.property with O(1) hash lookup",
            "Returns undefined/null cleanly if node or property does not exist",
        ],
    },
    {
        "task_key": "expression-engine/m7-helpers",
        "specialization": "expression-engine",
        "milestone": "M7",
        "title": "JavaScript Standard Helpers Compatibility",
        "description": "Built-in methods for String, Math, Date, and Array manipulations.",
        "progress_weight": 2.0,
        "validation_level": "L2",
        "dependencies": ["expression-engine/m7-evaluator"],
        "allowed_files": ["crates/n8n-expression/src/helpers.rs"],
        "exclusive_files": ["crates/n8n-expression/src/helpers.rs"],
        "shared_read_files": [],
        "acceptance_criteria": [
            "String methods (trim, split, replace, toLowerCase)",
            "Date parsing and formatting matching JS output",
        ],
    },

    # ==========================================================================
    # MILESTONE 8: VALIDATION (4 tasks | 4.0 weight)
    # ==========================================================================
    {
        "task_key": "validation/m8-cycle-detection",
        "specialization": "validation",
        "milestone": "M8",
        "title": "DAG Cycle Detection & Validation",
        "description": "Detects illegal circular dependencies in workflow execution graphs.",
        "progress_weight": 1.0,
        "validation_level": "L1",
        "dependencies": [],
        "allowed_files": ["crates/n8n-validation/src/cycle.rs"],
        "exclusive_files": ["crates/n8n-validation/src/cycle.rs"],
        "shared_read_files": ["crates/n8n-validation/src/lib.rs"],
        "acceptance_criteria": [
            "Rejects workflows with cycles in standard non-loop nodes",
            "Allows validated LoopOverItems cycles",
        ],
    },
    {
        "task_key": "validation/m8-node-uniqueness",
        "specialization": "validation",
        "milestone": "M8",
        "title": "Node Name Uniqueness Validator",
        "description": "Ensures all node names within a workflow are globally unique.",
        "progress_weight": 1.0,
        "validation_level": "L1",
        "dependencies": ["validation/m8-cycle-detection"],
        "allowed_files": ["crates/n8n-validation/src/uniqueness.rs"],
        "exclusive_files": ["crates/n8n-validation/src/uniqueness.rs"],
        "shared_read_files": [],
        "acceptance_criteria": [
            "Flags duplicate node names with actionable validation errors",
            "Case-insensitive comparison for reserved node labels",
        ],
    },
    {
        "task_key": "validation/m8-dangling-connections",
        "specialization": "validation",
        "milestone": "M8",
        "title": "Dangling Connections & Slot Validator",
        "description": "Verifies that connections target valid nodes and valid output/input slot indices.",
        "progress_weight": 1.0,
        "validation_level": "L1",
        "dependencies": ["validation/m8-cycle-detection"],
        "allowed_files": ["crates/n8n-validation/src/connections.rs"],
        "exclusive_files": ["crates/n8n-validation/src/connections.rs"],
        "shared_read_files": [],
        "acceptance_criteria": [
            "Detects connections pointing to non-existent node IDs",
            "Flags connections with out-of-bounds output slot indices",
        ],
    },
    {
        "task_key": "validation/m8-parameters",
        "specialization": "validation",
        "milestone": "M8",
        "title": "Node Parameter Conformance Validator",
        "description": "Validates required parameters and type constraints against node definitions.",
        "progress_weight": 1.0,
        "validation_level": "L1",
        "dependencies": ["validation/m8-cycle-detection"],
        "allowed_files": ["crates/n8n-validation/src/parameters.rs"],
        "exclusive_files": ["crates/n8n-validation/src/parameters.rs"],
        "shared_read_files": [],
        "acceptance_criteria": [
            "Validates required fields are present",
            "Checks numeric ranges and string length constraints",
        ],
    },

    # ==========================================================================
    # MILESTONE 9: INTEGRATION & CONFORMANCE (4 tasks | 9.0 weight)
    # ==========================================================================
    {
        "task_key": "integration/m9-conformance-harness",
        "specialization": "integration",
        "milestone": "M9",
        "title": "Rust vs Node.js Conformance Test Harness",
        "description": "Automated harness executing identical workflows on Rust and comparing against Node.js.",
        "progress_weight": 3.0,
        "validation_level": "L3",
        "dependencies": ["runtime-kernel/m1-runner", "node-system/m5-traits"],
        "allowed_files": ["tests/conformance.rs"],
        "exclusive_files": ["tests/conformance.rs"],
        "shared_read_files": [],
        "acceptance_criteria": [
            "Executes 20 test workflows on both runtimes",
            "100% match on output data and execution status",
        ],
    },
    {
        "task_key": "integration/m9-golden-replays",
        "specialization": "integration",
        "milestone": "M9",
        "title": "Golden Replay Fixture Verification Suite",
        "description": "Replays golden test fixtures across triggers, polling, and branching workflows.",
        "progress_weight": 2.0,
        "validation_level": "L3",
        "dependencies": ["integration/m9-conformance-harness"],
        "allowed_files": ["tests/trigger_lifecycle.rs", "tests/reference_fixtures.rs"],
        "exclusive_files": ["tests/trigger_lifecycle.rs", "tests/reference_fixtures.rs"],
        "shared_read_files": [],
        "acceptance_criteria": [
            "Verifies exact match on golden fixture status strings",
            "Ensures zero regression on trigger lifecycle events",
        ],
    },
    {
        "task_key": "integration/m9-benchmark",
        "specialization": "integration",
        "milestone": "M9",
        "title": "Criterion Throughput & Memory Benchmark Suite",
        "description": "Benchmarks execution speed and memory footprints against baseline.",
        "progress_weight": 2.0,
        "validation_level": "L2",
        "dependencies": ["integration/m9-conformance-harness"],
        "allowed_files": ["benches/runtime_benchmark.rs"],
        "exclusive_files": ["benches/runtime_benchmark.rs"],
        "shared_read_files": [],
        "acceptance_criteria": [
            "Demonstrates at least 5x speedup over Node.js for 10k items",
            "Verifies RAM usage remains within budget",
        ],
    },
    {
        "task_key": "integration/m9-legacy-lego-adapter",
        "specialization": "integration",
        "milestone": "M9",
        "title": "LEGO TypeScript Package Boundary Conformance",
        "description": "Ensures full compatibility with existing TypeScript LEGO modules.",
        "progress_weight": 2.0,
        "validation_level": "L2",
        "dependencies": ["integration/m9-conformance-harness"],
        "allowed_files": ["packages/workflow-lego/test/01-boundary.test.mjs"],
        "exclusive_files": ["packages/workflow-lego/test/01-boundary.test.mjs"],
        "shared_read_files": [],
        "acceptance_criteria": [
            "All 40 Node.js / TypeScript LEGO tests pass without regression",
            "Module import boundaries stay intact",
        ],
    },

    # ==========================================================================
    # MILESTONE 10: SECURITY & SANDBOX (4 tasks | 5.0 weight)
    # ==========================================================================
    {
        "task_key": "security/m10-fs-sandbox",
        "specialization": "security",
        "milestone": "M10",
        "title": "Workspace Filesystem Sandbox Boundary Guard",
        "description": "Blocks path traversal and forbids writes outside the task workspace directory.",
        "progress_weight": 2.0,
        "validation_level": "L1",
        "dependencies": [],
        "allowed_files": ["tools/arena-executor/fs_guard.py"],
        "exclusive_files": ["tools/arena-executor/fs_guard.py"],
        "shared_read_files": [],
        "acceptance_criteria": [
            "Blocks ../ path traversal attempts",
            "Raises SecurityError if code tries writing outside sandbox",
        ],
    },
    {
        "task_key": "security/m10-env-isolation",
        "specialization": "security",
        "milestone": "M10",
        "title": "Sensitive Environment Variable Sanitizer",
        "description": "Strips tokens, secrets, and system environment variables from worker processes.",
        "progress_weight": 1.0,
        "validation_level": "L1",
        "dependencies": ["security/m10-fs-sandbox"],
        "allowed_files": ["tools/arena-executor/executor.py"],
        "exclusive_files": ["tools/arena-executor/executor.py"],
        "shared_read_files": [],
        "acceptance_criteria": [
            "Removes SUPABASE_KEY, GITHUB_TOKEN, and internal keys from child processes",
            "Passes environment isolation test suite",
        ],
    },
    {
        "task_key": "security/m10-timeout-watchdog",
        "specialization": "security",
        "milestone": "M10",
        "title": "Preemptive Execution Timeout Watchdog",
        "description": "Terminates hanging or infinite-looping worker processes automatically.",
        "progress_weight": 1.0,
        "validation_level": "L1",
        "dependencies": ["security/m10-fs-sandbox"],
        "allowed_files": ["tools/arena-executor/timeout.py"],
        "exclusive_files": ["tools/arena-executor/timeout.py"],
        "shared_read_files": [],
        "acceptance_criteria": [
            "Kills processes that exceed configured timeout threshold",
            "Logs TIMEOUT_EXCEEDED security event",
        ],
    },
    {
        "task_key": "security/m10-prototype-pollution",
        "specialization": "security",
        "milestone": "M10",
        "title": "Prototype Pollution & Reserved Attribute Guard",
        "description": "Prevents JSON prototype pollution vulnerabilities (__proto__, constructor).",
        "progress_weight": 1.0,
        "validation_level": "L1",
        "dependencies": ["security/m10-fs-sandbox"],
        "allowed_files": ["crates/n8n-execution-data/src/security.rs"],
        "exclusive_files": ["crates/n8n-execution-data/src/security.rs"],
        "shared_read_files": [],
        "acceptance_criteria": [
            "Blocks __proto__ and constructor injection in JSON records",
            "Passes prototype pollution regression tests",
        ],
    },
]
